Approach:

1) Reading first dataset(receipts):
    cleaning "_id"
    Cleaning "dates"
    Creating a new table named "receipts_rewards" from rewardsReceiptItemList column
        
2) Reading second dataset(users)
        cleaning "_id"
        cleaning "dates"
        
3) Reading third dataset(brands)
        cleaning "_id"
        cleaning "dates"
        
4) Connecting jupyter notebook to postgres database at local server
        loading 3 datasets and "receipts_rewards"as tables into postgres database
        
5) Writing sql query to answer business questions

6) Data Quality issues 

7) Communication with Stakeholder

In [97]:
#Importing Libraries

import pandas as pd
import json
from datetime import datetime
import numpy as np
import sqlalchemy
import psycopg2

## First Dataset (receipts)

In [98]:
#Reading first dataset (receipts)

receipts = pd.read_json('./receipts.json', lines = True)

In [99]:
receipts

,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId
0,{'$oid': '5ff1e1eb0a720f0523000575'},500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},500.0,{'$date': 1609632000000},5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
2,{'$oid': '5ff1e1f10a720f052300057a'},5.0,All-receipts receipt bonus,{'$date': 1609687537000},{'$date': 1609687537000},NaN,{'$date': 1609687542000},NaN,5.0,{'$date': 1609632000000},1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b
3,{'$oid': '5ff1e1ee0a7214ada100056f'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6
4,{'$oid': '5ff1e1d20a7214ada1000561'},5.0,All-receipts receipt bonus,{'$date': 1609687506000},{'$date': 1609687506000},{'$date': 1609687511000},{'$date': 1609687511000},{'$date': 1609687506000},5.0,{'$date': 1609601106000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
5,{'$oid': '5ff1e1e40a7214ada1000566'},750.0,"Receipt number 1 completed, bonus point schedu...",{'$date': 1609687524000},{'$date': 1609687524000},{'$date': 1609687525000},{'$date': 1609687530000},{'$date': 1609687525000},750.0,{'$date': 1609601124000},1.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,3.25,5ff1e1e4cfcf6c399c274ac3
6,{'$oid': '5ff1e1cd0a720f052300056f'},5.0,All-receipts receipt bonus,{'$date': 1609687501000},{'$date': 1609687501000},{'$date': 1609687502000},{'$date': 1609687502000},{'$date': 1609687502000},5.0,{'$date': 1609687501000},1.0,"[{'brandCode': 'MISSION', 'competitorRewardsGr...",FINISHED,2.23,5ff1e194b6a9d73a3a9f1052
7,{'$oid': '5ff1e1a40a720f0523000569'},500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687460000},{'$date': 1609687460000},{'$date': 1609687461000},{'$date': 1609687461000},{'$date': 1609687461000},500.0,{'$date': 1609027200000},1.0,"[{'barcode': '046000832517', 'brandCode': 'BRA...",FINISHED,10.00,5ff1e194b6a9d73a3a9f1052
8,{'$oid': '5ff1e1ed0a7214ada100056e'},5.0,All-receipts receipt bonus,{'$date': 1609687533000},{'$date': 1609687533000},{'$date': 1609687534000},{'$date': 1609687538000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,20.00,5ff1e1eacfcf6c399c274ae6
9,{'$oid': '5ff1e1eb0a7214ada100056b'},250.0,"Receipt number 3 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},250.0,{'$date': 1609632000000},3.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,20.00,5ff1e1eacfcf6c399c274ae6
10,{'$oid': '5ff1e1c50a720f052300056c'},100.0,"Receipt number 6 completed, bonus point schedu...",{'$date': 1609687493000},{'$date': 1609687493000},{'$date': 1609687493000},{'$date': 1609687493000},{'$date': 1609687493000},100.0,{'$date': 1609601093000},1.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
11,{'$oid': '5ff1e1a10a720f0523000568'},750.0,"Receipt number 1 completed, bonus point schedu...",{'$date': 1609687457000},{'$date': 1609687457000},{'$date': 1609688360000},{'$date': 1609688360000},{'$date': 1609687459000},750.0,{'$date': 1609545600000},5.0,"[{'barcode': '013562300631', 'description': 'A...",FINISHED,50.00,5ff1e194b6a9d73a3a9f1052
12,{'$oid': '5ff1e1b60a7214ada100055c'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687478000},{'$date': 1609687478000},NaN,{'$date': 1609687478000},NaN,8850.0,{'$date': 1612365878000},10.0,"[{'barcode': '034100573065', 'description': 'M...",FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
13,{'$oid': '5f9c74f70a7214ad07000037'},750.0,"Receipt number 1 completed, bonus point schedu...",{'$date': 1604089079000},{'$date': 1604089079000},NaN,{'$date': 1609687494000},{'$date': 1604089080000},750.0,{'$date': 1604002679000},11.0,"[{'barcode': '075925306254', 'competitiveProdu...",REJECTED,1.00,5f9c74f7c88c1415cbddb839
14,{'$oid': '5ff1e1b20a7214ada100055a'},300.0,"Receipt number 4 completed, bonus point schedu...",{'$date': 1609687474000},{'$date': 1609687474000},{'$date': 1609687475000},{'$date': 1609687475000},{'$date': 1609687475000},300.0,{'$date': 1612365875000},1.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
15,{'$oid': '5ff1e1e90a7214ada1000569'},NaN,NaN,{'$date': 1609687529000},{'$date': 1609687529000},NaN,{'$date': 1609687529000},NaN,NaN,NaN,0.0,"[{'needsFetchReview': True, 'needsFetchReviewR...",FLAGGED,0.00,5ff1e1e9b6a9d73a3a9f10f6
16,{'$oid': '5ff1e1df0a7214ada1000564'},750.0,"Receipt number 1 completed, bonus point schedu...",{'$date': 1609687519000},{'$date': 1609687519000},{'$date': 1609687520000},{'$date': 1609687525000},{'$date': 1609687519000},750.0,{'$date': 1609601119000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.00,5ff1e1dfcfcf6c399c274ab3
17,{'$oid': '5ff1e1b40a7214ada100055b'},750.0,"Receipt number 1 completed, bonus point schedu...",{'$date': 1609687476000},{'$date': 1609687476000},NaN,{'$date': 1609687477000},{'$date': 1609687476000},750.0,{'$date': 1609601076000},1.0,"[{'barcode': '075925306254', 'competitiveProdu...",FLAGGED,1.00,5ff1e1b4cfcf6c399c274a54
18,{'$oid': '5ff1e1eb0a720f0523000576'},300.0,"Receipt number 4 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687532000},{'$date': 1609687536000},{'$date': 1609687532000},300.0,{'$date': 1609632000000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
19,{'$oid': '5ff1e1c80a720f052300056d'},5.0,All-receipts receipt bonus,{'$date': 1609687496000},{'$date': 1609687496000},{'$date': 1609687502000},{'$date': 1609687502000},{'$date': 1609687496000},5.0,{'$date': 1609601096000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
20,{'$oid': '5f9c74f90a7214ad07000038'},300.0,"Receipt number 4 completed, bonus point schedu...",{'$date': 1604089081000},{'$date': 1604089081000},{'$date': 1609688395000},{'$date': 1609688395000},{'$date': 1609688395000},389.2,{'$date': 1604002681000},6.0,"[{'barcode': '075925306254', 'competitiveProdu...",FINISHED,14.00,5f9c74e3f1937815bd2c1d73
21,{'$oid': '5ff1e1960a720f0523000567'},750.0,"Receipt number 1 completed, bonus point schedu...",{'$date': 1609687446000},{'$date': 1609687446000},{'$date': 1609687450000},{'$date': 1609687450000},{'$date': 1609687450000},750.0,{'$date': 1609601046000},1.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e196cfcf6c399c274a38
22,{'$oid': '5ff1e1ec0a7214ada100056c'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687532000},{'$date': 1609687532000},{'$date': 1609687532000},{'$date': 1609687537000},{'$date': 1609687532000},150.0,{'$date': 1609632000000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,21.00,5ff1e1eacfcf6c399c274ae6
23,{'$oid': '5ff1e1d70a720f0523000571'},40.0,COMPLETE_PARTNER_RECEIPT,{'$date': 1609687511000},{'$date': 1609687511000},{'$date': 1609687512000},{'$date': 1609687512000},{'$date': 1609687512000},185.0,{'$date': 1609601111000},2.0,"[{'barcode': '041000168468', 'description': 'K...",FINISHED,2.00,5ff1e194b6a9d73a3a9f1052
24,{'$oid': '5ff1e1c60a7214ada100055e'},5.0,All-receipts receipt bonus,{'$date': 1609687494000},{'$date': 1609687494000},{'$date': 1609687499000},{'$date': 1609687499000},{'$date': 1609687494000},5.0,{'$date': 1609601094000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
25,{'$oid': '5ff1e1ee0a7214ada1000570'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687535000},{'$date': 1609687540000},{'$date': 1609687535000},5.0,{'$date': 1609632000000},5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,27.00,5ff1e1eacfcf6c399c274ae6
26,{'$oid': '5ff1e1cf0a720f0523000570'},5.0,All-receipts receipt bonus,{'$date': 1609687503000},{'$date': 1609687503000},{'$date': 1609687509000},{'$date': 1609687509000},{'$date': 1609687503000},5.0,{'$date': 1609601103000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
27,{'$oid': '5ff1e1e10a720f0523000572'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1609687521000},{'$date': 1609687521000},{'$date': 1609687521000},{'$date': 1609687526000},{'$date': 1609687521000},35.0,{'$date': 1609601121000},1.0,"[{'barcode': '079400066619', 'competitiveProdu...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
28,{'$oid': '5ff1e1d40a7214ada1000562'},NaN,NaN,{'$date': 1609687508000},{'$date': 1609687508000},NaN,{'$date': 1609687508000},NaN,NaN,{'$date': 1509321600000},3.0,"[{'deleted': True, 'description': 'DELETED ITE...",REJECTED,3.00,5ff1e194b6a9d73a3a9f1052
29,{'$oid': '5ff1e1ee0a720f0523000578'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,27.00,5ff1e1eacfcf6c399c274ae6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1089,{'$oid': '603cbbb50a720fde100003e3'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614592949000},{'$date': 1614592949000},NaN,{'$date': 1614592950000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1090,{'$oid': '603cadab0a720fde100003d6'},NaN,NaN,{'$date': 1614589355175},{'$date': 1614589355175},NaN,{'$date': 1614589355175},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1091,{'$oid': '603c8cdf0a7217c72c0003bb'},NaN,NaN,{'$date': 1614580959190},{'$date': 1614580959190},NaN,{'$date': 1614580959190},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1092,{'$oid': '603d30e60a7217c72c00043f'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614622950000},{'$date': 1614622950000},NaN,{'$date': 1614622951000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1093,{'$oid': '603c65060a720fde10000395'},NaN,NaN,{'$date': 1614570758407},{'$date': 1614570758407},NaN,{'$date': 1614570758407},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1094,{'$oid': '603d5d6c0a7217c72c000463'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614634348000},{'$date': 1614634348000},NaN,{'$date': 1614634349000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1095,{'$oid': '603d760e0a720fde1000048e'},NaN,NaN,{'$date': 1614640654772},{'$date': 1614640654772},NaN,{'$date': 1614640654772},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1096,{'$oid': '603d59e70a7217c72c00045f'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614633447000},{'$date': 1614633447000},NaN,{'$date': 1614633448000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1097,{'$oid': '603c5ba30a720fde1000038d'},NaN,NaN,{'$date': 1614568355733},{'$date': 1614568355733},NaN,{'$date': 1614568355733},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1098,{'$oid': '603c51160a7217c72c00038b'},NaN,NaN,{'$date': 1614565654329},{'$date': 1614565654329},NaN,{'$date': 1614565654329},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1099,{'$oid': '603d40250a720fde10000459'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614626853000},{'$date': 1614626853000},NaN,{'$date': 1614626854000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1100,{'$oid': '603c88240a7217c72c0003b8'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614579748000},{'$date': 1614579748000},NaN,{'$date': 1614579749000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1101,{'$oid': '603cba880a7217c72c0003e0'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614592648000},{'$date': 1614592648000},NaN,{'$date': 1614592649000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1102,{'$oid': '603cd4570a7217c72c0003f5'},NaN,NaN,{'$date': 1614599255734},{'$date': 1614599255734},NaN,{'$date': 1614599255734},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1103,{'$oid': '603cd57d0a7217c72c0003f6'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614599549000},{'$date': 1614599549000},NaN,{'$date': 1614599550000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1104,{'$oid': '603cf2ce0a7217c72c000413'},NaN,NaN,{'$date': 1614607054396},{'$date': 1614607054396},NaN,{'$date': 1614607054396},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1105,{'$oid': '603cac7d0a7217c72c0003d7'},NaN,NaN,{'$date': 1614589053696},{'$date': 1614589053696},NaN,{'$date': 1614589053696},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1106,{'$oid': '603c7c6c0a7217c72c0003b3'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614576748000},{'$date': 1614576748000},NaN,{'$date': 1614576749000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1107,{'$oid': '603d28b60a720fde10000445'},NaN,NaN,{'$date': 1614620854867},{'$date': 1614620854867},NaN,{'$date': 1614620854867},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1108,{'$oid': '603ca44a0a720fde100003d0'},NaN,NaN,{'$date': 1614586954244},{'$date': 1614586954244},NaN,{'$date': 1614586954244},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1109,{'$oid': '603c4a0e0a720fde10000380'},NaN,NaN,{'$date': 1614563854494},{'$date': 1614563854494},NaN,{'$date': 1614563854494},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1110,{'$oid': '603c6adf0a720fde1000039a'},NaN,NaN,{'$date': 1614572255736},{'$date': 1614572255736},NaN,{'$date': 1614572255736},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1111,{'$oid': '603c9e6e0a720fde100003c7'},NaN,NaN,{'$date': 1614585454307},{'$date': 1614585454307},NaN,{'$date': 1614585454307},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1112,{'$oid': '603c3d240a720fde10000373'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614560548000},{'$date': 1614560548000},NaN,{'$date': 1614560549000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1113,{'$oid': '603cc2bc0a720fde100003e9'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614594748000},{'$date': 1614594748000},NaN,{'$date': 1614594749000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1114,{'$oid': '603cc0630a720fde100003e6'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614594147000},{'$date': 1614594147000},NaN,{'$date': 1614594148000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1115,{'$oid': '603d0b710a720fde1000042a'},NaN,NaN,{'$date': 1614613361873},{'$date': 1614613361873},NaN,{'$date': 1614613361873},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1116,{'$oid': '603cf5290a720fde10000413'},NaN,NaN,{'$date': 1614607657664},{'$date': 1614607657664},NaN,{'$date': 1614607657664},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1117,{'$oid': '603ce7100a7217c72c000405'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614604048000},{'$date': 1614604048000},NaN,{'$date': 1614604049000},NaN,25.0,{'$date': 1597622400000},2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1118,{'$oid': '603c4fea0a7217c72c000389'},NaN,NaN,{'$date': 1614565354962},{'$date': 1614565354962},NaN,{'$date': 1614565354962},NaN,NaN,NaN,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33

In [100]:
receipts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1119 entries, 0 to 1118
Data columns (total 15 columns):
_id                        1119 non-null object
bonusPointsEarned          544 non-null float64
bonusPointsEarnedReason    544 non-null object
createDate                 1119 non-null object
dateScanned                1119 non-null object
finishedDate               568 non-null object
modifyDate                 1119 non-null object
pointsAwardedDate          537 non-null object
pointsEarned               609 non-null float64
purchaseDate               671 non-null object
purchasedItemCount         635 non-null float64
rewardsReceiptItemList     679 non-null object
rewardsReceiptStatus       1119 non-null object
totalSpent                 684 non-null float64
userId                     1119 non-null object
dtypes: float64(4), object(11)
memory usage: 131.2+ KB

## Cleaning the "_id" from receipts dataset

In [101]:
#There are "_id" to be cleaned in multiple dataset, below is the function to clean the "_id" column

def clean_id(column, dataset):   
    variable = []
    for i in range(0, len(dataset)):
        for key, value in column[i].items():
            variable.append(value)
            
            
    return variable

In [102]:
receipts['_id'] = clean_id(receipts['_id'],receipts) #Clean id from receipts table

## Cleaning the "dates" from receipts dataset

In [103]:
#There are multiple "date" column to be cleaned in multiple dataset, below is the function to clean the "date" column

def clean_date(column, dataset): #fuction to clean date in the dataset
    
    var = []
    
    for i in range(0,len(dataset)):
        if(type(column[i])) == dict:
            for key, value in column[i].items():
                var.append(value)
        else:
            var.append(None)
        
    return var

In [104]:
createDate = clean_date(receipts['createDate'],receipts)
receipts['createDate'] = pd.to_datetime(createDate, unit = 'ms')

dateScanned = clean_date(receipts['dateScanned'],receipts)
receipts['dateScanned'] = pd.to_datetime(dateScanned, unit = 'ms')

finishedDate = clean_date(receipts['finishedDate'],receipts)
receipts['finishedDate'] = pd.to_datetime(finishedDate, unit = 'ms')

modifyDate = clean_date(receipts['modifyDate'],receipts)
receipts['modifyDate'] = pd.to_datetime(modifyDate, unit = 'ms')

pointsAwardedDate = clean_date(receipts['pointsAwardedDate'],receipts)
receipts['pointsAwardedDate'] = pd.to_datetime(pointsAwardedDate, unit = 'ms')

purchaseDate = clean_date(receipts['purchaseDate'],receipts)
receipts['purchaseDate'] = pd.to_datetime(purchaseDate, unit = 'ms')

In [105]:
#Making all the column names in lower case in order to write sql query
receipts.columns= receipts.columns.str.lower()

In [106]:
receipts

,_id,bonuspointsearned,bonuspointsearnedreason,createdate,datescanned,finisheddate,modifydate,pointsawardeddate,pointsearned,purchasedate,purchaseditemcount,rewardsreceiptitemlist,rewardsreceiptstatus,totalspent,userid
0,5ff1e1eb0a720f0523000575,500.0,"Receipt number 2 completed, bonus point schedu...",2021-01-03 15:25:31.000,2021-01-03 15:25:31.000,2021-01-03 15:25:31,2021-01-03 15:25:36.000,2021-01-03 15:25:31,500.0,2021-01-03 00:00:00,5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:43.000,2021-01-03 15:24:43.000,2021-01-03 15:24:43,2021-01-03 15:24:48.000,2021-01-03 15:24:43,150.0,2021-01-02 15:24:43,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
2,5ff1e1f10a720f052300057a,5.0,All-receipts receipt bonus,2021-01-03 15:25:37.000,2021-01-03 15:25:37.000,NaT,2021-01-03 15:25:42.000,NaT,5.0,2021-01-03 00:00:00,1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b
3,5ff1e1ee0a7214ada100056f,5.0,All-receipts receipt bonus,2021-01-03 15:25:34.000,2021-01-03 15:25:34.000,2021-01-03 15:25:34,2021-01-03 15:25:39.000,2021-01-03 15:25:34,5.0,2021-01-03 00:00:00,4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6
4,5ff1e1d20a7214ada1000561,5.0,All-receipts receipt bonus,2021-01-03 15:25:06.000,2021-01-03 15:25:06.000,2021-01-03 15:25:11,2021-01-03 15:25:11.000,2021-01-03 15:25:06,5.0,2021-01-02 15:25:06,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
5,5ff1e1e40a7214ada1000566,750.0,"Receipt number 1 completed, bonus point schedu...",2021-01-03 15:25:24.000,2021-01-03 15:25:24.000,2021-01-03 15:25:25,2021-01-03 15:25:30.000,2021-01-03 15:25:25,750.0,2021-01-02 15:25:24,1.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,3.25,5ff1e1e4cfcf6c399c274ac3
6,5ff1e1cd0a720f052300056f,5.0,All-receipts receipt bonus,2021-01-03 15:25:01.000,2021-01-03 15:25:01.000,2021-01-03 15:25:02,2021-01-03 15:25:02.000,2021-01-03 15:25:02,5.0,2021-01-03 15:25:01,1.0,"[{'brandCode': 'MISSION', 'competitorRewardsGr...",FINISHED,2.23,5ff1e194b6a9d73a3a9f1052
7,5ff1e1a40a720f0523000569,500.0,"Receipt number 2 completed, bonus point schedu...",2021-01-03 15:24:20.000,2021-01-03 15:24:20.000,2021-01-03 15:24:21,2021-01-03 15:24:21.000,2021-01-03 15:24:21,500.0,2020-12-27 00:00:00,1.0,"[{'barcode': '046000832517', 'brandCode': 'BRA...",FINISHED,10.00,5ff1e194b6a9d73a3a9f1052
8,5ff1e1ed0a7214ada100056e,5.0,All-receipts receipt bonus,2021-01-03 15:25:33.000,2021-01-03 15:25:33.000,2021-01-03 15:25:34,2021-01-03 15:25:38.000,2021-01-03 15:25:34,5.0,2021-01-03 00:00:00,5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,20.00,5ff1e1eacfcf6c399c274ae6
9,5ff1e1eb0a7214ada100056b,250.0,"Receipt number 3 completed, bonus point schedu...",2021-01-03 15:25:31.000,2021-01-03 15:25:31.000,2021-01-03 15:25:31,2021-01-03 15:25:36.000,2021-01-03 15:25:31,250.0,2021-01-03 00:00:00,3.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,20.00,5ff1e1eacfcf6c399c274ae6
10,5ff1e1c50a720f052300056c,100.0,"Receipt number 6 completed, bonus point schedu...",2021-01-03 15:24:53.000,2021-01-03 15:24:53.000,2021-01-03 15:24:53,2021-01-03 15:24:53.000,2021-01-03 15:24:53,100.0,2021-01-02 15:24:53,1.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
11,5ff1e1a10a720f0523000568,750.0,"Receipt number 1 completed, bonus point schedu...",2021-01-03 15:24:17.000,2021-01-03 15:24:17.000,2021-01-03 15:39:20,2021-01-03 15:39:20.000,2021-01-03 15:24:19,750.0,2021-01-02 00:00:00,5.0,"[{'barcode': '013562300631', 'description': 'A...",FINISHED,50.00,5ff1e194b6a9d73a3a9f1052
12,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,"[{'barcode': '034100573065', 'description': 'M...",FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
13,5f9c74f70a7214ad07000037,750.0,"Receipt number 1 completed, bonus point schedu...",2020-10-30 20:17:59.000,2020-10-30 20:17:59.000,NaT,2021-01-03 15:24:54.000,2020-10-30 20:18:00,750.0,2020-10-29 20:17:59,11.0,"[{'barcode': '075925306254', 'competitiveProdu...",REJECTED,1.00,5f9c74f7c88c1415cbddb839
14,5ff1e1b20a7214ada100055a,300.0,"Receipt number 4 completed, bonus point schedu...",2021-01-03 15:24:34.000,2021-01-03 15:24:34.000,2021-01-03 15:24:35,2021-01-03 15:24:35.000,2021-01-03 15:24:35,300.0,2021-02-03 15:24:35,1.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
15,5ff1e1e90a7214ada1000569,NaN,NaN,2021-01-03 15:25:29.000,2021-01-03 15:25:29.000,NaT,2021-01-03 15:25:29.000,NaT,NaN,NaT,0.0,"[{'needsFetchReview': True, 'needsFetchReviewR...",FLAGGED,0.00,5ff1e1e9b6a9d73a3a9f10f6
16,5ff1e1df0a7214ada1000564,750.0,"Receipt number 1 completed, bonus point schedu...",2021-01-03 15:25:19.000,2021-01-03 15:25:19.000,2021-01-03 15:25:20,2021-01-03 15:25:25.000,2021-01-03 15:25:19,750.0,2021-01-02 15:25:19,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.00,5ff1e1dfcfcf6c399c274ab3
17,5ff1e1b40a7214ada100055b,750.0,"Receipt number 1 completed, bonus point schedu...",2021-01-03 15:24:36.000,2021-01-03 15:24:36.000,NaT,2021-01-03 15:24:37.000,2021-01-03 15:24:36,750.0,2021-01-02 15:24:36,1.0,"[{'barcode': '075925306254', 'competitiveProdu...",FLAGGED,1.00,5ff1e1b4cfcf6c399c274a54
18,5ff1e1eb0a720f0523000576,300.0,"Receipt number 4 completed, bonus point schedu...",2021-01-03 15:25:31.000,2021-01-03 15:25:31.000,2021-01-03 15:25:32,2021-01-03 15:25:36.000,2021-01-03 15:25:32,300.0,2021-01-03 00:00:00,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
19,5ff1e1c80a720f052300056d,5.0,All-receipts receipt bonus,2021-01-03 15:24:56.000,2021-01-03 15:24:56.000,2021-01-03 15:25:02,2021-01-03 15:25:02.000,2021-01-03 15:24:56,5.0,2021-01-02 15:24:56,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
20,5f9c74f90a7214ad07000038,300.0,"Receipt number 4 completed, bonus point schedu...",2020-10-30 20:18:01.000,2020-10-30 20:18:01.000,2021-01-03 15:39:55,2021-01-03 15:39:55.000,2021-01-03 15:39:55,389.2,2020-10-29 20:18:01,6.0,"[{'barcode': '075925306254', 'competitiveProdu...",FINISHED,14.00,5f9c74e3f1937815bd2c1d73
21,5ff1e1960a720f0523000567,750.0,"Receipt number 1 completed, bonus point schedu...",2021-01-03 15:24:06.000,2021-01-03 15:24:06.000,2021-01-03 15:24:10,2021-01-03 15:24:10.000,2021-01-03 15:24:10,750.0,2021-01-02 15:24:06,1.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e196cfcf6c399c274a38
22,5ff1e1ec0a7214ada100056c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:25:32.000,2021-01-03 15:25:32.000,2021-01-03 15:25:32,2021-01-03 15:25:37.000,2021-01-03 15:25:32,150.0,2021-01-03 00:00:00,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,21.00,5ff1e1eacfcf6c399c274ae6
23,5ff1e1d70a720f0523000571,40.0,COMPLETE_PARTNER_RECEIPT,2021-01-03 15:25:11.000,2021-01-03 15:25:11.000,2021-01-03 15:25:12,2021-01-03 15:25:12.000,2021-01-03 15:25:12,185.0,2021-01-02 15:25:11,2.0,"[{'barcode': '041000168468', 'description': 'K...",FINISHED,2.00,5ff1e194b6a9d73a3a9f1052
24,5ff1e1c60a7214ada100055e,5.0,All-receipts receipt bonus,2021-01-03 15:24:54.000,2021-01-03 15:24:54.000,2021-01-03 15:24:59,2021-01-03 15:24:59.000,2021-01-03 15:24:54,5.0,2021-01-02 15:24:54,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
25,5ff1e1ee0a7214ada1000570,5.0,All-receipts receipt bonus,2021-01-03 15:25:34.000,2021-01-03 15:25:34.000,2021-01-03 15:25:35,2021-01-03 15:25:40.000,2021-01-03 15:25:35,5.0,2021-01-03 00:00:00,5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,27.00,5ff1e1eacfcf6c399c274ae6
26,5ff1e1cf0a720f0523000570,5.0,All-receipts receipt bonus,2021-01-03 15:25:03.000,2021-01-03 15:25:03.000,2021-01-03 15:25:09,2021-01-03 15:25:09.000,2021-01-03 15:25:03,5.0,2021-01-02 15:25:03,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
27,5ff1e1e10a720f0523000572,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-01-03 15:25:21.000,2021-01-03 15:25:21.000,2021-01-03 15:25:21,2021-01-03 15:25:26.000,2021-01-03 15:25:21,35.0,2021-01-02 15:25:21,1.0,"[{'barcode': '079400066619', 'competitiveProdu...",FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
28,5ff1e1d40a7214ada1000562,NaN,NaN,2021-01-03 15:25:08.000,2021-01-03 15:25:08.000,NaT,2021-01-03 15:25:08.000,NaT,NaN,2017-10-30 00:00:00,3.0,"[{'deleted': True, 'description': 'DELETED ITE...",REJECTED,3.00,5ff1e194b6a9d73a3a9f1052
29,5ff1e1ee0a720f0523000578,5.0,All-receipts receipt bonus,2021-01-03 15:25:34.000,2021-01-03 15:25:34.000,2021-01-03 15:25:34,2021-01-03 15:25:39.000,2021-01-03 15:25:34,5.0,2021-01-03 00:00:00,4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,27.00,5ff1e1eacfcf6c399c274ae6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1089,603cbbb50a720fde100003e3,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 10:02:29.000,2021-03-01 10:02:29.000,NaT,2021-03-01 10:02:30.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1090,603cadab0a720fde100003d6,NaN,NaN,2021-03-01 09:02:35.175,2021-03-01 09:02:35.175,NaT,2021-03-01 09:02:35.175,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1091,603c8cdf0a7217c72c0003bb,NaN,NaN,2021-03-01 06:42:39.190,2021-03-01 06:42:39.190,NaT,2021-03-01 06:42:39.190,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1092,603d30e60a7217c72c00043f,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 18:22:30.000,2021-03-01 18:22:30.000,NaT,2021-03-01 18:22:31.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1093,603c65060a720fde10000395,NaN,NaN,2021-03-01 03:52:38.407,2021-03-01 03:52:38.407,NaT,2021-03-01 03:52:38.407,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1094,603d5d6c0a7217c72c000463,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 21:32:28.000,2021-03-01 21:32:28.000,NaT,2021-03-01 21:32:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1095,603d760e0a720fde1000048e,NaN,NaN,2021-03-01 23:17:34.772,2021-03-01 23:17:34.772,NaT,2021-03-01 23:17:34.772,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1096,603d59e70a7217c72c00045f,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 21:17:27.000,2021-03-01 21:17:27.000,NaT,2021-03-01 21:17:28.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1097,603c5ba30a720fde1000038d,NaN,NaN,2021-03-01 03:12:35.733,2021-03-01 03:12:35.733,NaT,2021-03-01 03:12:35.733,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1098,603c51160a7217c72c00038b,NaN,NaN,2021-03-01 02:27:34.329,2021-03-01 02:27:34.329,NaT,2021-03-01 02:27:34.329,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1099,603d40250a720fde10000459,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 19:27:33.000,2021-03-01 19:27:33.000,NaT,2021-03-01 19:27:34.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1100,603c88240a7217c72c0003b8,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 06:22:28.000,2021-03-01 06:22:28.000,NaT,2021-03-01 06:22:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1101,603cba880a7217c72c0003e0,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 09:57:28.000,2021-03-01 09:57:28.000,NaT,2021-03-01 09:57:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1102,603cd4570a7217c72c0003f5,NaN,NaN,2021-03-01 11:47:35.734,2021-03-01 11:47:35.734,NaT,2021-03-01 11:47:35.734,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1103,603cd57d0a7217c72c0003f6,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 11:52:29.000,2021-03-01 11:52:29.000,NaT,2021-03-01 11:52:30.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1104,603cf2ce0a7217c72c000413,NaN,NaN,2021-03-01 13:57:34.396,2021-03-01 13:57:34.396,NaT,2021-03-01 13:57:34.396,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1105,603cac7d0a7217c72c0003d7,NaN,NaN,2021-03-01 08:57:33.696,2021-03-01 08:57:33.696,NaT,2021-03-01 08:57:33.696,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1106,603c7c6c0a7217c72c0003b3,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 05:32:28.000,2021-03-01 05:32:28.000,NaT,2021-03-01 05:32:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1107,603d28b60a720fde10000445,NaN,NaN,2021-03-01 17:47:34.867,2021-03-01 17:47:34.867,NaT,2021-03-01 17:47:34.867,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1108,603ca44a0a720fde100003d0,NaN,NaN,2021-03-01 08:22:34.244,2021-03-01 08:22:34.244,NaT,2021-03-01 08:22:34.244,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1109,603c4a0e0a720fde10000380,NaN,NaN,2021-03-01 01:57:34.494,2021-03-01 01:57:34.494,NaT,2021-03-01 01:57:34.494,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1110,603c6adf0a720fde1000039a,NaN,NaN,2021-03-01 04:17:35.736,2021-03-01 04:17:35.736,NaT,2021-03-01 04:17:35.736,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1111,603c9e6e0a720fde100003c7,NaN,NaN,2021-03-01 07:57:34.307,2021-03-01 07:57:34.307,NaT,2021-03-01 07:57:34.307,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1112,603c3d240a720fde10000373,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 01:02:28.000,2021-03-01 01:02:28.000,NaT,2021-03-01 01:02:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1113,603cc2bc0a720fde100003e9,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 10:32:28.000,2021-03-01 10:32:28.000,NaT,2021-03-01 10:32:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1114,603cc0630a720fde100003e6,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 10:22:27.000,2021-03-01 10:22:27.000,NaT,2021-03-01 10:22:28.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1115,603d0b710a720fde1000042a,NaN,NaN,2021-03-01 15:42:41.873,2021-03-01 15:42:41.873,NaT,2021-03-01 15:42:41.873,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1116,603cf5290a720fde10000413,NaN,NaN,2021-03-01 14:07:37.664,2021-03-01 14:07:37.664,NaT,2021-03-01 14:07:37.664,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
1117,603ce7100a7217c72c000405,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 13:07:28.000,2021-03-01 13:07:28.000,NaT,2021-03-01 13:07:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...",REJECTED,34.96,5fc961c3b8cfca11a077dd33
1118,603c4fea0a7217c72c000389,NaN,NaN,2021-03-01 02:22:34.962,2021-03-01 02:22:34.962,NaT,2021-03-01 02:22:34.962,NaT,NaN,NaT,NaN,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33

Looking at the above dataset we can see that every column is being cleaned except for the "rewardsreceiptitemlist". This column is a list of dictionaries with uneven keys. The idea is to get all the distinct keys from all the dictionaries and give them the corresponding values and form a different table(receipts_rewards). Along with these keys, I have added column "_id" which can help to join both the tables

## Creating  new table named "rewards_receipt" out of column "rewards_receiptItemList" from receipts dataset

In [107]:
receipts['rewardsreceiptitemlist']

0       [{'barcode': '4011', 'description': 'ITEM NOT ...
1       [{'barcode': '4011', 'description': 'ITEM NOT ...
2       [{'needsFetchReview': False, 'partnerItemId': ...
3       [{'barcode': '4011', 'description': 'ITEM NOT ...
4       [{'barcode': '4011', 'description': 'ITEM NOT ...
5       [{'barcode': '4011', 'description': 'ITEM NOT ...
6       [{'brandCode': 'MISSION', 'competitorRewardsGr...
7       [{'barcode': '046000832517', 'brandCode': 'BRA...
8       [{'barcode': '4011', 'description': 'ITEM NOT ...
9       [{'barcode': '4011', 'description': 'ITEM NOT ...
10      [{'barcode': '4011', 'description': 'ITEM NOT ...
11      [{'barcode': '013562300631', 'description': 'A...
12      [{'barcode': '034100573065', 'description': 'M...
13      [{'barcode': '075925306254', 'competitiveProdu...
14      [{'barcode': '4011', 'description': 'ITEM NOT ...
15      [{'needsFetchReview': True, 'needsFetchReviewR...
16      [{'barcode': '4011', 'description': 'ITEM NOT ...
17      [{'barcode': '075925306254', 'competitiveProdu...
18      [{'barcode': '4011', 'description': 'ITEM NOT ...
19      [{'barcode': '4011', 'description': 'ITEM NOT ...
20      [{'barcode': '075925306254', 'competitiveProdu...
21      [{'barcode': '4011', 'description': 'ITEM NOT ...
22      [{'barcode': '4011', 'description': 'ITEM NOT ...
23      [{'barcode': '041000168468', 'description': 'K...
24      [{'barcode': '4011', 'description': 'ITEM NOT ...
25      [{'barcode': '4011', 'description': 'ITEM NOT ...
26      [{'barcode': '4011', 'description': 'ITEM NOT ...
27      [{'barcode': '079400066619', 'competitiveProdu...
28      [{'deleted': True, 'description': 'DELETED ITE...
29      [{'barcode': '4011', 'description': 'ITEM NOT ...
                              ...
1089    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1090                                                  NaN
1091                                                  NaN
1092    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1093                                                  NaN
1094    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1095                                                  NaN
1096    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1097                                                  NaN
1098                                                  NaN
1099    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1100    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1101    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1102                                                  NaN
1103    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1104                                                  NaN
1105                                                  NaN
1106    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1107                                                  NaN
1108                                                  NaN
1109                                                  NaN
1110                                                  NaN
1111                                                  NaN
1112    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1113    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1114    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1115                                                  NaN
1116                                                  NaN
1117    [{'barcode': 'B076FJ92M4', 'description': 'mue...
1118                                                  NaN
Name: rewardsreceiptitemlist, Length: 1119, dtype: object

## Taking a temporary df to create a subset of receipts dataset, so we can flatten the "rewardsreceiptitemlist" column. this will open up the dictionary.

In [108]:
df = receipts[['_id','rewardsreceiptitemlist']]

In [109]:
out = []
for n, row in df.iterrows():
    if (type(row['rewardsreceiptitemlist'])) == list:
        for item in row['rewardsreceiptitemlist']:
            row['flatten'] = item
            out += [row.copy()]
    else:
        out+= [row.copy()]


flattened_df = pd.DataFrame(out)

In [110]:
flattened_df

#From the below output I can see that there are list of dictionaries in rewardsreceiptitemlist column 
#(Example: Interpreting that "_id" for index 1 has two dictionaries)

,_id,rewardsreceiptitemlist,flatten
0,5ff1e1eb0a720f0523000575,"[{'barcode': '4011', 'description': 'ITEM NOT ...","{'barcode': '4011', 'description': 'ITEM NOT F..."
1,5ff1e1bb0a720f052300056b,"[{'barcode': '4011', 'description': 'ITEM NOT ...","{'barcode': '4011', 'description': 'ITEM NOT F..."
1,5ff1e1bb0a720f052300056b,"[{'barcode': '4011', 'description': 'ITEM NOT ...","{'barcode': '028400642255', 'description': 'DO..."
2,5ff1e1f10a720f052300057a,"[{'needsFetchReview': False, 'partnerItemId': ...","{'needsFetchReview': False, 'partnerItemId': '..."
3,5ff1e1ee0a7214ada100056f,"[{'barcode': '4011', 'description': 'ITEM NOT ...","{'barcode': '4011', 'description': 'ITEM NOT F..."
4,5ff1e1d20a7214ada1000561,"[{'barcode': '4011', 'description': 'ITEM NOT ...","{'barcode': '4011', 'description': 'ITEM NOT F..."
4,5ff1e1d20a7214ada1000561,"[{'barcode': '4011', 'description': 'ITEM NOT ...","{'barcode': '1234', 'finalPrice': '2.56', 'ite..."
5,5ff1e1e40a7214ada1000566,"[{'barcode': '4011', 'description': 'ITEM NOT ...","{'barcode': '4011', 'description': 'ITEM NOT F..."
6,5ff1e1cd0a720f052300056f,"[{'brandCode': 'MISSION', 'competitorRewardsGr...","{'brandCode': 'MISSION', 'competitorRewardsGro..."
7,5ff1e1a40a720f0523000569,"[{'barcode': '046000832517', 'brandCode': 'BRA...","{'barcode': '046000832517', 'brandCode': 'BRAN..."
8,5ff1e1ed0a7214ada100056e,"[{'barcode': '4011', 'description': 'ITEM NOT ...","{'barcode': '4011', 'description': 'ITEM NOT F..."
9,5ff1e1eb0a7214ada100056b,"[{'barcode': '4011', 'description': 'ITEM NOT ...","{'barcode': '4011', 'description': 'ITEM NOT F..."
10,5ff1e1c50a720f052300056c,"[{'barcode': '4011', 'description': 'ITEM NOT ...","{'barcode': '4011', 'description': 'ITEM NOT F..."
11,5ff1e1a10a720f0523000568,"[{'barcode': '013562300631', 'description': 'A...","{'barcode': '013562300631', 'description': 'An..."
12,5ff1e1b60a7214ada100055c,"[{'barcode': '034100573065', 'description': 'M...","{'barcode': '034100573065', 'description': 'MI..."
12,5ff1e1b60a7214ada100055c,"[{'barcode': '034100573065', 'description': 'M...","{'barcode': '034100573065', 'description': 'MI..."
12,5ff1e1b60a7214ada100055c,"[{'barcode': '034100573065', 'description': 'M...","{'barcode': '034100573065', 'description': 'MI..."
12,5ff1e1b60a7214ada100055c,"[{'barcode': '034100573065', 'description': 'M...","{'barcode': '034100573065', 'description': 'MI..."
12,5ff1e1b60a7214ada100055c,"[{'barcode': '034100573065', 'description': 'M...","{'barcode': '034100573065', 'description': 'MI..."
12,5ff1e1b60a7214ada100055c,"[{'barcode': '034100573065', 'description': 'M...","{'barcode': '034100573065', 'description': 'MI..."
12,5ff1e1b60a7214ada100055c,"[{'barcode': '034100573065', 'description': 'M...","{'barcode': '034100573065', 'description': 'MI..."
12,5ff1e1b60a7214ada100055c,"[{'barcode': '034100573065', 'description': 'M...","{'barcode': '034100573065', 'description': 'MI..."
12,5ff1e1b60a7214ada100055c,"[{'barcode': '034100573065', 'description': 'M...","{'barcode': '034100573065', 'description': 'MI..."
12,5ff1e1b60a7214ada100055c,"[{'barcode': '034100573065', 'description': 'M...","{'barcode': '034100573065', 'description': 'MI..."
13,5f9c74f70a7214ad07000037,"[{'barcode': '075925306254', 'competitiveProdu...","{'barcode': '075925306254', 'competitiveProduc..."
13,5f9c74f70a7214ad07000037,"[{'barcode': '075925306254', 'competitiveProdu...","{'needsFetchReview': True, 'needsFetchReviewRe..."
13,5f9c74f70a7214ad07000037,"[{'barcode': '075925306254', 'competitiveProdu...","{'needsFetchReview': True, 'needsFetchReviewRe..."
13,5f9c74f70a7214ad07000037,"[{'barcode': '075925306254', 'competitiveProdu...","{'needsFetchReview': True, 'needsFetchReviewRe..."
13,5f9c74f70a7214ad07000037,"[{'barcode': '075925306254', 'competitiveProdu...","{'needsFetchReview': True, 'needsFetchReviewRe..."
13,5f9c74f70a7214ad07000037,"[{'barcode': '075925306254', 'competitiveProdu...","{'needsFetchReview': True, 'needsFetchReviewRe..."
...,...,...,...
1098,603c51160a7217c72c00038b,NaN,NaN
1099,603d40250a720fde10000459,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B076FJ92M4', 'description': 'muel..."
1099,603d40250a720fde10000459,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B07BRRLSVC', 'description': 'thin..."
1100,603c88240a7217c72c0003b8,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B076FJ92M4', 'description': 'muel..."
1100,603c88240a7217c72c0003b8,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B07BRRLSVC', 'description': 'thin..."
1101,603cba880a7217c72c0003e0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B076FJ92M4', 'description': 'muel..."
1101,603cba880a7217c72c0003e0,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B07BRRLSVC', 'description': 'thin..."
1102,603cd4570a7217c72c0003f5,NaN,NaN
1103,603cd57d0a7217c72c0003f6,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B076FJ92M4', 'description': 'muel..."
1103,603cd57d0a7217c72c0003f6,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B07BRRLSVC', 'description': 'thin..."
1104,603cf2ce0a7217c72c000413,NaN,NaN
1105,603cac7d0a7217c72c0003d7,NaN,NaN
1106,603c7c6c0a7217c72c0003b3,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B076FJ92M4', 'description': 'muel..."
1106,603c7c6c0a7217c72c0003b3,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B07BRRLSVC', 'description': 'thin..."
1107,603d28b60a720fde10000445,NaN,NaN
1108,603ca44a0a720fde100003d0,NaN,NaN
1109,603c4a0e0a720fde10000380,NaN,NaN
1110,603c6adf0a720fde1000039a,NaN,NaN
1111,603c9e6e0a720fde100003c7,NaN,NaN
1112,603c3d240a720fde10000373,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B076FJ92M4', 'description': 'muel..."
1112,603c3d240a720fde10000373,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B07BRRLSVC', 'description': 'thin..."
1113,603cc2bc0a720fde100003e9,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B076FJ92M4', 'description': 'muel..."
1113,603cc2bc0a720fde100003e9,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B07BRRLSVC', 'description': 'thin..."
1114,603cc0630a720fde100003e6,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B076FJ92M4', 'description': 'muel..."
1114,603cc0630a720fde100003e6,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B07BRRLSVC', 'description': 'thin..."
1115,603d0b710a720fde1000042a,NaN,NaN
1116,603cf5290a720fde10000413,NaN,NaN
1117,603ce7100a7217c72c000405,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B076FJ92M4', 'description': 'muel..."
1117,603ce7100a7217c72c000405,"[{'barcode': 'B076FJ92M4', 'description': 'mue...","{'barcode': 'B07BRRLSVC', 'description': 'thin..."
1118,603c4fea0a7217c72c000389,NaN,NaN

In [111]:
receipts = pd.merge(receipts,flattened_df, on = '_id') #Merging the flattened_df to my original receipts

In [112]:
#Since we have flattened_df we no longer need "rewardsreceiptitemlist", so dropping it from the dataset
receipts.drop('rewardsreceiptitemlist_x', inplace = True, axis = 1)
receipts.drop('rewardsreceiptitemlist_y', inplace = True, axis = 1)

In [113]:
#Renaming flatten as "rewardsreceiptitemlist" 
receipts.rename(columns = {'flatten':'rewardsreceiptitemlist'}, inplace = True)

In [114]:
#The code below will provide unique list of keys in all the dictionary (This is our column for the new table to be created)  

all_keys = set()

for i in range(len(receipts)):
    if (type(receipts['rewardsreceiptitemlist'][i])) == dict:
        all_keys = all_keys.union(set(receipts['rewardsreceiptitemlist'][i].keys()))

In [115]:
all_keys #These are all the unique keys from the 'rewardsreceiptitemlist' column

{'barcode',
 'brandCode',
 'competitiveProduct',
 'competitorRewardsGroup',
 'deleted',
 'description',
 'discountedItemPrice',
 'finalPrice',
 'itemNumber',
 'itemPrice',
 'metabriteCampaignId',
 'needsFetchReview',
 'needsFetchReviewReason',
 'originalFinalPrice',
 'originalMetaBriteBarcode',
 'originalMetaBriteDescription',
 'originalMetaBriteItemPrice',
 'originalMetaBriteQuantityPurchased',
 'originalReceiptItemText',
 'partnerItemId',
 'pointsEarned',
 'pointsNotAwardedReason',
 'pointsPayerId',
 'preventTargetGapPoints',
 'priceAfterCoupon',
 'quantityPurchased',
 'rewardsGroup',
 'rewardsProductPartnerId',
 'targetPrice',
 'userFlaggedBarcode',
 'userFlaggedDescription',
 'userFlaggedNewItem',
 'userFlaggedPrice',
 'userFlaggedQuantity'}

In [116]:
rewards_receipt = pd.DataFrame(columns = ['_id']+list(all_keys))  #Structure of new table to be created
rewards_receipt

Empty DataFrame
Columns: [_id, finalPrice, priceAfterCoupon, preventTargetGapPoints, originalMetaBriteBarcode, userFlaggedNewItem, needsFetchReviewReason, rewardsProductPartnerId, originalFinalPrice, needsFetchReview, rewardsGroup, originalMetaBriteDescription, pointsPayerId, originalMetaBriteItemPrice, discountedItemPrice, description, userFlaggedBarcode, competitiveProduct, userFlaggedDescription, partnerItemId, pointsEarned, targetPrice, metabriteCampaignId, deleted, quantityPurchased, barcode, competitorRewardsGroup, userFlaggedPrice, brandCode, itemPrice, userFlaggedQuantity, originalMetaBriteQuantityPurchased, originalReceiptItemText, itemNumber, pointsNotAwardedReason]
Index: []

[0 rows x 35 columns]

In [117]:
# Giving all the value to the respected key to the new structured table. Null will be assigned to the key if they dont have values

columns = ['_id']+list(all_keys)
dictionary = dict()


for each in columns:
    dictionary[each] = []
    
for i in range(len(receipts)):
    dictionary['_id'].append(receipts['_id'].values[0])
    tempDic = receipts['rewardsreceiptitemlist'][i]
    
    for each in all_keys:
        if (type(tempDic)) == dict:
            dictionary[each].append(tempDic.get(each,np.nan)) 
        else:
            dictionary[each].append(np.nan)

In [118]:
rewards_receipt = pd.DataFrame(dictionary)
rewards_receipt

,_id,finalPrice,priceAfterCoupon,preventTargetGapPoints,originalMetaBriteBarcode,userFlaggedNewItem,needsFetchReviewReason,rewardsProductPartnerId,originalFinalPrice,needsFetchReview,...,barcode,competitorRewardsGroup,userFlaggedPrice,brandCode,itemPrice,userFlaggedQuantity,originalMetaBriteQuantityPurchased,originalReceiptItemText,itemNumber,pointsNotAwardedReason
0,5ff1e1eb0a720f0523000575,26.00,NaN,True,NaN,True,NaN,NaN,NaN,False,...,4011,NaN,26.00,NaN,26.00,5.0,NaN,NaN,NaN,NaN
1,5ff1e1eb0a720f0523000575,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4011,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
2,5ff1e1eb0a720f0523000575,10.00,NaN,True,NaN,True,USER_FLAGGED,5332f5fbe4b03c9a25efd0ba,NaN,True,...,028400642255,NaN,10.00,NaN,10.00,1.0,NaN,NaN,NaN,Action not allowed for user and CPG
3,5ff1e1eb0a720f0523000575,NaN,NaN,True,NaN,True,NaN,NaN,NaN,False,...,NaN,NaN,26.00,NaN,NaN,3.0,NaN,NaN,NaN,NaN
4,5ff1e1eb0a720f0523000575,28.00,NaN,True,NaN,True,NaN,NaN,NaN,False,...,4011,NaN,28.00,NaN,28.00,4.0,NaN,NaN,NaN,NaN
5,5ff1e1eb0a720f0523000575,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4011,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
6,5ff1e1eb0a720f0523000575,2.56,NaN,True,NaN,True,USER_FLAGGED,NaN,NaN,True,...,1234,NaN,2.56,NaN,2.56,3.0,NaN,NaN,NaN,NaN
7,5ff1e1eb0a720f0523000575,3.25,NaN,True,028400642255,NaN,NaN,5332f5fbe4b03c9a25efd0ba,NaN,False,...,4011,NaN,NaN,NaN,3.25,NaN,NaN,NaN,NaN,Action not allowed for user and CPG
8,5ff1e1eb0a720f0523000575,2.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,TACO BELL TACO SHELLS,NaN,MISSION,2.23,NaN,NaN,MSSN TORTLLA,NaN,NaN
9,5ff1e1eb0a720f0523000575,10.00,NaN,NaN,NaN,NaN,NaN,5332f5f3e4b03c9a25efd0ae,NaN,NaN,...,046000832517,NaN,NaN,BRAND,10.00,NaN,NaN,NaN,NaN,Action not allowed for user and CPG
10,5ff1e1eb0a720f0523000575,20.00,NaN,True,NaN,True,NaN,NaN,NaN,False,...,4011,NaN,20.00,NaN,20.00,5.0,NaN,NaN,NaN,NaN
11,5ff1e1eb0a720f0523000575,20.00,NaN,True,NaN,True,NaN,NaN,NaN,False,...,4011,NaN,20.00,NaN,20.00,3.0,NaN,NaN,NaN,NaN
12,5ff1e1eb0a720f0523000575,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4011,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
13,5ff1e1eb0a720f0523000575,50.00,NaN,NaN,NaN,NaN,POINTS_GREATER_THAN_THRESHOLD,5332f5f3e4b03c9a25efd0ae,NaN,True,...,013562300631,NaN,NaN,NaN,50.00,NaN,1.0,NaN,013562300631,Action not allowed for user and CPG
14,5ff1e1eb0a720f0523000575,29,NaN,NaN,NaN,NaN,NaN,5332f709e4b03c9a25efd0f1,NaN,NaN,...,034100573065,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
15,5ff1e1eb0a720f0523000575,29,NaN,NaN,NaN,NaN,NaN,5332f709e4b03c9a25efd0f1,NaN,NaN,...,034100573065,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
16,5ff1e1eb0a720f0523000575,29,NaN,NaN,NaN,NaN,NaN,5332f709e4b03c9a25efd0f1,NaN,NaN,...,034100573065,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
17,5ff1e1eb0a720f0523000575,29,NaN,NaN,NaN,NaN,NaN,5332f709e4b03c9a25efd0f1,NaN,NaN,...,034100573065,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
18,5ff1e1eb0a720f0523000575,29,NaN,NaN,NaN,NaN,NaN,5332f709e4b03c9a25efd0f1,NaN,NaN,...,034100573065,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
19,5ff1e1eb0a720f0523000575,29,NaN,NaN,NaN,NaN,NaN,5332f709e4b03c9a25efd0f1,NaN,NaN,...,034100573065,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
20,5ff1e1eb0a720f0523000575,29,NaN,NaN,NaN,NaN,NaN,5332f709e4b03c9a25efd0f1,NaN,NaN,...,034100573065,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
21,5ff1e1eb0a720f0523000575,29,NaN,NaN,NaN,NaN,NaN,5332f709e4b03c9a25efd0f1,NaN,NaN,...,034100573065,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
22,5ff1e1eb0a720f0523000575,29,NaN,NaN,NaN,NaN,NaN,5332f709e4b03c9a25efd0f1,NaN,NaN,...,034100573065,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
23,5ff1e1eb0a720f0523000575,29,NaN,NaN,NaN,NaN,NaN,5332f709e4b03c9a25efd0f1,NaN,NaN,...,034100573065,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN
24,5ff1e1eb0a720f0523000575,1,NaN,NaN,NaN,NaN,NaN,559c2234e4b06aca36af13c6,NaN,NaN,...,075925306254,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
25,5ff1e1eb0a720f0523000575,NaN,NaN,True,NaN,True,USER_FLAGGED,NaN,NaN,True,...,NaN,NaN,29.00,NaN,NaN,1.0,NaN,NaN,NaN,NaN
26,5ff1e1eb0a720f0523000575,NaN,NaN,True,NaN,True,USER_FLAGGED,NaN,NaN,True,...,NaN,NaN,29.00,NaN,NaN,1.0,NaN,NaN,NaN,NaN
27,5ff1e1eb0a720f0523000575,NaN,NaN,True,NaN,True,USER_FLAGGED,NaN,NaN,True,...,NaN,NaN,29.00,NaN,NaN,1.0,NaN,NaN,NaN,NaN
28,5ff1e1eb0a720f0523000575,NaN,NaN,True,NaN,True,USER_FLAGGED,NaN,NaN,True,...,NaN,NaN,29.00,NaN,NaN,1.0,NaN,NaN,NaN,NaN
29,5ff1e1eb0a720f0523000575,NaN,NaN,True,NaN,True,USER_FLAGGED,NaN,NaN,True,...,NaN,NaN,29.00,NaN,NaN,1.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7351,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7352,5ff1e1eb0a720f0523000575,22.97,22.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B076FJ92M4,NaN,NaN,NaN,22.97,NaN,NaN,mueller austria hypergrind precision electric ...,NaN,NaN
7353,5ff1e1eb0a720f0523000575,11.99,11.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B07BRRLSVC,NaN,NaN,NaN,11.99,NaN,NaN,thindust summer face mask - sun protection nec...,NaN,NaN
7354,5ff1e1eb0a720f0523000575,22.97,22.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B076FJ92M4,NaN,NaN,NaN,22.97,NaN,NaN,mueller austria hypergrind precision electric ...,NaN,NaN
7355,5ff1e1eb0a720f0523000575,11.99,11.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B07BRRLSVC,NaN,NaN,NaN,11.99,NaN,NaN,thindust summer face mask - sun protection nec...,NaN,NaN
7356,5ff1e1eb0a720f0523000575,22.97,22.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B076FJ92M4,NaN,NaN,NaN,22.97,NaN,NaN,mueller austria hypergrind precision electric ...,NaN,NaN
7357,5ff1e1eb0a720f0523000575,11.99,11.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B07BRRLSVC,NaN,NaN,NaN,11.99,NaN,NaN,thindust summer face mask - sun protection nec...,NaN,NaN
7358,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7359,5ff1e1eb0a720f0523000575,22.97,22.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B076FJ92M4,NaN,NaN,NaN,22.97,NaN,NaN,mueller austria hypergrind precision electric ...,NaN,NaN
7360,5ff1e1eb0a720f0523000575,11.99,11.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B07BRRLSVC,NaN,NaN,NaN,11.99,NaN,NaN,thindust summer face mask - sun protection nec...,NaN,NaN
7361,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7362,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7363,5ff1e1eb0a720f0523000575,22.97,22.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B076FJ92M4,NaN,NaN,NaN,22.97,NaN,NaN,mueller austria hypergrind precision electric ...,NaN,NaN
7364,5ff1e1eb0a720f0523000575,11.99,11.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B07BRRLSVC,NaN,NaN,NaN,11.99,NaN,NaN,thindust summer face mask - sun protection nec...,NaN,NaN
7365,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7366,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7367,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7368,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7369,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7370,5ff1e1eb0a720f0523000575,22.97,22.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B076FJ92M4,NaN,NaN,NaN,22.97,NaN,NaN,mueller austria hypergrind precision electric ...,NaN,NaN
7371,5ff1e1eb0a720f0523000575,11.99,11.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B07BRRLSVC,NaN,NaN,NaN,11.99,NaN,NaN,thindust summer face mask - sun protection nec...,NaN,NaN
7372,5ff1e1eb0a720f0523000575,22.97,22.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B076FJ92M4,NaN,NaN,NaN,22.97,NaN,NaN,mueller austria hypergrind precision electric ...,NaN,NaN
7373,5ff1e1eb0a720f0523000575,11.99,11.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B07BRRLSVC,NaN,NaN,NaN,11.99,NaN,NaN,thindust summer face mask - sun protection nec...,NaN,NaN
7374,5ff1e1eb0a720f0523000575,22.97,22.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B076FJ92M4,NaN,NaN,NaN,22.97,NaN,NaN,mueller austria hypergrind precision electric ...,NaN,NaN
7375,5ff1e1eb0a720f0523000575,11.99,11.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B07BRRLSVC,NaN,NaN,NaN,11.99,NaN,NaN,thindust summer face mask - sun protection nec...,NaN,NaN
7376,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7377,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7378,5ff1e1eb0a720f0523000575,22.97,22.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B076FJ92M4,NaN,NaN,NaN,22.97,NaN,NaN,mueller austria hypergrind precision electric ...,NaN,NaN
7379,5ff1e1eb0a720f0523000575,11.99,11.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B07BRRLSVC,NaN,NaN,NaN,11.99,NaN,NaN,thindust summer face mask - sun protection nec...,NaN,NaN
7380,5ff1e1eb0a720f0523000575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
#Converting all the column names in lower case in order to write sql query
rewards_receipt.columns= rewards_receipt.columns.str.lower()

In [120]:
#"rewardsreceiptitemlist" column is no longer needed in the original receipts dataset
#Since a new table rewards_receipt was created from this rewardsreceiptitemlist column

receipts.drop('rewardsreceiptitemlist', inplace = True, axis = 1)

In [121]:
receipts

,_id,bonuspointsearned,bonuspointsearnedreason,createdate,datescanned,finisheddate,modifydate,pointsawardeddate,pointsearned,purchasedate,purchaseditemcount,rewardsreceiptstatus,totalspent,userid
0,5ff1e1eb0a720f0523000575,500.0,"Receipt number 2 completed, bonus point schedu...",2021-01-03 15:25:31.000,2021-01-03 15:25:31.000,2021-01-03 15:25:31,2021-01-03 15:25:36.000,2021-01-03 15:25:31,500.0,2021-01-03 00:00:00,5.0,FINISHED,26.00,5ff1e1eacfcf6c399c274ae6
1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:43.000,2021-01-03 15:24:43.000,2021-01-03 15:24:43,2021-01-03 15:24:48.000,2021-01-03 15:24:43,150.0,2021-01-02 15:24:43,2.0,FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
2,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:43.000,2021-01-03 15:24:43.000,2021-01-03 15:24:43,2021-01-03 15:24:48.000,2021-01-03 15:24:43,150.0,2021-01-02 15:24:43,2.0,FINISHED,11.00,5ff1e194b6a9d73a3a9f1052
3,5ff1e1f10a720f052300057a,5.0,All-receipts receipt bonus,2021-01-03 15:25:37.000,2021-01-03 15:25:37.000,NaT,2021-01-03 15:25:42.000,NaT,5.0,2021-01-03 00:00:00,1.0,REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b
4,5ff1e1ee0a7214ada100056f,5.0,All-receipts receipt bonus,2021-01-03 15:25:34.000,2021-01-03 15:25:34.000,2021-01-03 15:25:34,2021-01-03 15:25:39.000,2021-01-03 15:25:34,5.0,2021-01-03 00:00:00,4.0,FINISHED,28.00,5ff1e1eacfcf6c399c274ae6
5,5ff1e1d20a7214ada1000561,5.0,All-receipts receipt bonus,2021-01-03 15:25:06.000,2021-01-03 15:25:06.000,2021-01-03 15:25:11,2021-01-03 15:25:11.000,2021-01-03 15:25:06,5.0,2021-01-02 15:25:06,2.0,FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
6,5ff1e1d20a7214ada1000561,5.0,All-receipts receipt bonus,2021-01-03 15:25:06.000,2021-01-03 15:25:06.000,2021-01-03 15:25:11,2021-01-03 15:25:11.000,2021-01-03 15:25:06,5.0,2021-01-02 15:25:06,2.0,FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
7,5ff1e1e40a7214ada1000566,750.0,"Receipt number 1 completed, bonus point schedu...",2021-01-03 15:25:24.000,2021-01-03 15:25:24.000,2021-01-03 15:25:25,2021-01-03 15:25:30.000,2021-01-03 15:25:25,750.0,2021-01-02 15:25:24,1.0,FINISHED,3.25,5ff1e1e4cfcf6c399c274ac3
8,5ff1e1cd0a720f052300056f,5.0,All-receipts receipt bonus,2021-01-03 15:25:01.000,2021-01-03 15:25:01.000,2021-01-03 15:25:02,2021-01-03 15:25:02.000,2021-01-03 15:25:02,5.0,2021-01-03 15:25:01,1.0,FINISHED,2.23,5ff1e194b6a9d73a3a9f1052
9,5ff1e1a40a720f0523000569,500.0,"Receipt number 2 completed, bonus point schedu...",2021-01-03 15:24:20.000,2021-01-03 15:24:20.000,2021-01-03 15:24:21,2021-01-03 15:24:21.000,2021-01-03 15:24:21,500.0,2020-12-27 00:00:00,1.0,FINISHED,10.00,5ff1e194b6a9d73a3a9f1052
10,5ff1e1ed0a7214ada100056e,5.0,All-receipts receipt bonus,2021-01-03 15:25:33.000,2021-01-03 15:25:33.000,2021-01-03 15:25:34,2021-01-03 15:25:38.000,2021-01-03 15:25:34,5.0,2021-01-03 00:00:00,5.0,FINISHED,20.00,5ff1e1eacfcf6c399c274ae6
11,5ff1e1eb0a7214ada100056b,250.0,"Receipt number 3 completed, bonus point schedu...",2021-01-03 15:25:31.000,2021-01-03 15:25:31.000,2021-01-03 15:25:31,2021-01-03 15:25:36.000,2021-01-03 15:25:31,250.0,2021-01-03 00:00:00,3.0,FINISHED,20.00,5ff1e1eacfcf6c399c274ae6
12,5ff1e1c50a720f052300056c,100.0,"Receipt number 6 completed, bonus point schedu...",2021-01-03 15:24:53.000,2021-01-03 15:24:53.000,2021-01-03 15:24:53,2021-01-03 15:24:53.000,2021-01-03 15:24:53,100.0,2021-01-02 15:24:53,1.0,FINISHED,1.00,5ff1e194b6a9d73a3a9f1052
13,5ff1e1a10a720f0523000568,750.0,"Receipt number 1 completed, bonus point schedu...",2021-01-03 15:24:17.000,2021-01-03 15:24:17.000,2021-01-03 15:39:20,2021-01-03 15:39:20.000,2021-01-03 15:24:19,750.0,2021-01-02 00:00:00,5.0,FINISHED,50.00,5ff1e194b6a9d73a3a9f1052
14,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
15,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
16,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
17,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
18,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
19,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
20,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
21,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
22,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
23,5ff1e1b60a7214ada100055c,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 15:24:38.000,2021-01-03 15:24:38.000,NaT,2021-01-03 15:24:38.000,NaT,8850.0,2021-02-03 15:24:38,10.0,FLAGGED,290.00,5ff1e194b6a9d73a3a9f1052
24,5f9c74f70a7214ad07000037,750.0,"Receipt number 1 completed, bonus point schedu...",2020-10-30 20:17:59.000,2020-10-30 20:17:59.000,NaT,2021-01-03 15:24:54.000,2020-10-30 20:18:00,750.0,2020-10-29 20:17:59,11.0,REJECTED,1.00,5f9c74f7c88c1415cbddb839
25,5f9c74f70a7214ad07000037,750.0,"Receipt number 1 completed, bonus point schedu...",2020-10-30 20:17:59.000,2020-10-30 20:17:59.000,NaT,2021-01-03 15:24:54.000,2020-10-30 20:18:00,750.0,2020-10-29 20:17:59,11.0,REJECTED,1.00,5f9c74f7c88c1415cbddb839
26,5f9c74f70a7214ad07000037,750.0,"Receipt number 1 completed, bonus point schedu...",2020-10-30 20:17:59.000,2020-10-30 20:17:59.000,NaT,2021-01-03 15:24:54.000,2020-10-30 20:18:00,750.0,2020-10-29 20:17:59,11.0,REJECTED,1.00,5f9c74f7c88c1415cbddb839
27,5f9c74f70a7214ad07000037,750.0,"Receipt number 1 completed, bonus point schedu...",2020-10-30 20:17:59.000,2020-10-30 20:17:59.000,NaT,2021-01-03 15:24:54.000,2020-10-30 20:18:00,750.0,2020-10-29 20:17:59,11.0,REJECTED,1.00,5f9c74f7c88c1415cbddb839
28,5f9c74f70a7214ad07000037,750.0,"Receipt number 1 completed, bonus point schedu...",2020-10-30 20:17:59.000,2020-10-30 20:17:59.000,NaT,2021-01-03 15:24:54.000,2020-10-30 20:18:00,750.0,2020-10-29 20:17:59,11.0,REJECTED,1.00,5f9c74f7c88c1415cbddb839
29,5f9c74f70a7214ad07000037,750.0,"Receipt number 1 completed, bonus point schedu...",2020-10-30 20:17:59.000,2020-10-30 20:17:59.000,NaT,2021-01-03 15:24:54.000,2020-10-30 20:18:00,750.0,2020-10-29 20:17:59,11.0,REJECTED,1.00,5f9c74f7c88c1415cbddb839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7351,603c51160a7217c72c00038b,NaN,NaN,2021-03-01 02:27:34.329,2021-03-01 02:27:34.329,NaT,2021-03-01 02:27:34.329,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7352,603d40250a720fde10000459,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 19:27:33.000,2021-03-01 19:27:33.000,NaT,2021-03-01 19:27:34.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7353,603d40250a720fde10000459,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 19:27:33.000,2021-03-01 19:27:33.000,NaT,2021-03-01 19:27:34.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7354,603c88240a7217c72c0003b8,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 06:22:28.000,2021-03-01 06:22:28.000,NaT,2021-03-01 06:22:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7355,603c88240a7217c72c0003b8,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 06:22:28.000,2021-03-01 06:22:28.000,NaT,2021-03-01 06:22:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7356,603cba880a7217c72c0003e0,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 09:57:28.000,2021-03-01 09:57:28.000,NaT,2021-03-01 09:57:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7357,603cba880a7217c72c0003e0,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 09:57:28.000,2021-03-01 09:57:28.000,NaT,2021-03-01 09:57:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7358,603cd4570a7217c72c0003f5,NaN,NaN,2021-03-01 11:47:35.734,2021-03-01 11:47:35.734,NaT,2021-03-01 11:47:35.734,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7359,603cd57d0a7217c72c0003f6,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 11:52:29.000,2021-03-01 11:52:29.000,NaT,2021-03-01 11:52:30.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7360,603cd57d0a7217c72c0003f6,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 11:52:29.000,2021-03-01 11:52:29.000,NaT,2021-03-01 11:52:30.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7361,603cf2ce0a7217c72c000413,NaN,NaN,2021-03-01 13:57:34.396,2021-03-01 13:57:34.396,NaT,2021-03-01 13:57:34.396,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7362,603cac7d0a7217c72c0003d7,NaN,NaN,2021-03-01 08:57:33.696,2021-03-01 08:57:33.696,NaT,2021-03-01 08:57:33.696,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7363,603c7c6c0a7217c72c0003b3,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 05:32:28.000,2021-03-01 05:32:28.000,NaT,2021-03-01 05:32:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7364,603c7c6c0a7217c72c0003b3,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 05:32:28.000,2021-03-01 05:32:28.000,NaT,2021-03-01 05:32:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7365,603d28b60a720fde10000445,NaN,NaN,2021-03-01 17:47:34.867,2021-03-01 17:47:34.867,NaT,2021-03-01 17:47:34.867,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7366,603ca44a0a720fde100003d0,NaN,NaN,2021-03-01 08:22:34.244,2021-03-01 08:22:34.244,NaT,2021-03-01 08:22:34.244,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7367,603c4a0e0a720fde10000380,NaN,NaN,2021-03-01 01:57:34.494,2021-03-01 01:57:34.494,NaT,2021-03-01 01:57:34.494,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7368,603c6adf0a720fde1000039a,NaN,NaN,2021-03-01 04:17:35.736,2021-03-01 04:17:35.736,NaT,2021-03-01 04:17:35.736,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7369,603c9e6e0a720fde100003c7,NaN,NaN,2021-03-01 07:57:34.307,2021-03-01 07:57:34.307,NaT,2021-03-01 07:57:34.307,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7370,603c3d240a720fde10000373,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 01:02:28.000,2021-03-01 01:02:28.000,NaT,2021-03-01 01:02:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7371,603c3d240a720fde10000373,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 01:02:28.000,2021-03-01 01:02:28.000,NaT,2021-03-01 01:02:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7372,603cc2bc0a720fde100003e9,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 10:32:28.000,2021-03-01 10:32:28.000,NaT,2021-03-01 10:32:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7373,603cc2bc0a720fde100003e9,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 10:32:28.000,2021-03-01 10:32:28.000,NaT,2021-03-01 10:32:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7374,603cc0630a720fde100003e6,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 10:22:27.000,2021-03-01 10:22:27.000,NaT,2021-03-01 10:22:28.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7375,603cc0630a720fde100003e6,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 10:22:27.000,2021-03-01 10:22:27.000,NaT,2021-03-01 10:22:28.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7376,603d0b710a720fde1000042a,NaN,NaN,2021-03-01 15:42:41.873,2021-03-01 15:42:41.873,NaT,2021-03-01 15:42:41.873,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7377,603cf5290a720fde10000413,NaN,NaN,2021-03-01 14:07:37.664,2021-03-01 14:07:37.664,NaT,2021-03-01 14:07:37.664,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33
7378,603ce7100a7217c72c000405,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 13:07:28.000,2021-03-01 13:07:28.000,NaT,2021-03-01 13:07:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7379,603ce7100a7217c72c000405,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 13:07:28.000,2021-03-01 13:07:28.000,NaT,2021-03-01 13:07:29.000,NaT,25.0,2020-08-17 00:00:00,2.0,REJECTED,34.96,5fc961c3b8cfca11a077dd33
7380,603c4fea0a7217c72c000389,NaN,NaN,2021-03-01 02:22:34.962,2021-03-01 02:22:34.962,NaT,2021-03-01 02:22:34.962,NaT,NaN,NaT,NaN,SUBMITTED,NaN,5fc961c3b8cfca11a077dd33

## Second Dataset (users)

In [122]:
#Reading code for the second dataset

users = pd.read_json('./users.json', lines = True)
users

,_id,active,createdDate,lastLogin,role,signUpSource,state
0,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
1,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
2,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
3,{'$oid': '5ff1e1eacfcf6c399c274ae6'},True,{'$date': 1609687530554},{'$date': 1609687530597},consumer,Email,WI
4,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
5,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
6,{'$oid': '5ff1e1e8cfcf6c399c274ad9'},True,{'$date': 1609687528354},{'$date': 1609687528392},consumer,Email,WI
7,{'$oid': '5ff1e1b7cfcf6c399c274a5a'},True,{'$date': 1609687479626},{'$date': 1609687479665},consumer,Email,WI
8,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
9,{'$oid': '5ff1e1f1cfcf6c399c274b0b'},True,{'$date': 1609687537564},{'$date': 1609687537599},consumer,Email,WI
10,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
11,{'$oid': '5ff1e1eacfcf6c399c274ae6'},True,{'$date': 1609687530554},{'$date': 1609687530597},consumer,Email,WI
12,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
13,{'$oid': '5ff1e1eacfcf6c399c274ae6'},True,{'$date': 1609687530554},{'$date': 1609687530597},consumer,Email,WI
14,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
15,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
16,{'$oid': '5ff1e1e4cfcf6c399c274ac3'},True,{'$date': 1609687524656},{'$date': 1609687524694},consumer,Email,WI
17,{'$oid': '5ff1e1b4cfcf6c399c274a54'},True,{'$date': 1609687476410},{'$date': 1609687476452},consumer,Email,WI
18,{'$oid': '5ff1e1eacfcf6c399c274ae6'},True,{'$date': 1609687530554},{'$date': 1609687530597},consumer,Email,WI
19,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
20,{'$oid': '5ff370c562fde912123a5e0e'},True,{'$date': 1609789637776},{'$date': 1609789850563},consumer,Email,WI
21,{'$oid': '5ff36d0362fde912123a5535'},True,{'$date': 1609788675973},{'$date': 1609788882944},consumer,Email,WI
22,{'$oid': '5ff36d83135e7011bcb864d6'},True,{'$date': 1609788803244},{'$date': 1609788803425},consumer,Email,WI
23,{'$oid': '5ff36c8862fde912123a538a'},True,{'$date': 1609788552943},{'$date': 1609788553141},consumer,Email,WI
24,{'$oid': '5ff370c562fde912123a5e0e'},True,{'$date': 1609789637776},{'$date': 1609789850563},consumer,Email,WI
25,{'$oid': '5ff36be7135e7011bcb856d3'},True,{'$date': 1609788391239},{'$date': 1609788592726},consumer,Email,WI
26,{'$oid': '5ff36d0362fde912123a5535'},True,{'$date': 1609788675973},{'$date': 1609788882944},consumer,Email,WI
27,{'$oid': '5ff36be7135e7011bcb856d3'},True,{'$date': 1609788391239},{'$date': 1609788592726},consumer,Email,WI
28,{'$oid': '5ff36a3862fde912123a4460'},True,{'$date': 1609787960352},{'$date': 1609788185340},consumer,Email,WI
29,{'$oid': '5ff36d0362fde912123a5535'},True,{'$date': 1609788675973},{'$date': 1609788882944},consumer,Email,WI
...,...,...,...,...,...,...,...
465,{'$oid': '5fa41775898c7a11a6bcef3e'},True,{'$date': 1604589429396},{'$date': 1614873722026},fetch-staff,Email,NaN
466,{'$oid': '5fa41775898c7a11a6bcef3e'},True,{'$date': 1604589429396},{'$date': 1614873722026},fetch-staff,Email,NaN
467,{'$oid': '5fa41775898c7a11a6bcef3e'},True,{'$date': 1604589429396},{'$date': 1614873722026},fetch-staff,Email,NaN
468,{'$oid': '5fa41775898c7a11a6bcef3e'},True,{'$date': 1604589429396},{'$date': 1614873722026},fetch-staff,Email,NaN
469,{'$oid': '5fa41775898c7a11a6bcef3e'},True,{'$date': 1604589429396},{'$date': 1614873722026},fetch-staff,Email,NaN
470,{'$oid': '5fa41775898c7a11a6bcef3e'},True,{'$date': 1604589429396},{'$date': 1614873722026},fetch-staff,Email,NaN
471,{'$oid': '5fa41775898c7a11a6bcef3e'},True,{'$date': 1604589429396},{'$date': 1614873722026},fetch-staff,Email,NaN
472,{'$oid': '5fa41775898c7a11a6bcef3e'},True,{'$date': 1604589429396},{'$date': 1614873722026},fetch-staff,Email,NaN
473,{'$oid': '5fa41775898c7a11a6bcef3e'},True,{'$date': 1604589429396},{'$date': 1614873722026},fetch-staff,Email,NaN
474,{'$oid': '5fa41775898c7a11a6bcef3e'},True,{'$date': 1604589429396},{'$date': 1614873722026},fetch-staff,Email,NaN
475,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
476,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
477,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
478,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
479,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
480,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
481,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
482,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
483,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
484,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
485,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
486,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
487,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
488,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
489,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
490,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
491,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
492,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
493,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN
494,{'$oid': '54943462e4b07e684157a532'},True,{'$date': 1418998882381},{'$date': 1614963143204},fetch-staff,NaN,NaN

In [123]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 7 columns):
_id             495 non-null object
active          495 non-null bool
createdDate     495 non-null object
lastLogin       433 non-null object
role            495 non-null object
signUpSource    447 non-null object
state           439 non-null object
dtypes: bool(1), object(6)
memory usage: 23.8+ KB

In [124]:
#Making all the column names in lower case in order to write sql query
users.columns= users.columns.str.lower()

In [125]:
#Using the "clean_id" function to clean the _id in users dataset
users['_id'] = clean_id(users['_id'],users)

In [126]:
#Using the "clean_date" function to clean the dates in users dataset

createdDate = clean_date(users['createddate'],users)
users['createddate'] = pd.to_datetime(createdDate, unit = 'ms')

lastLogin = clean_date(users['lastlogin'],users)
users['lastlogin'] = pd.to_datetime(lastLogin, unit = 'ms')

In [127]:
users #Cleaned second dataset

,_id,active,createddate,lastlogin,role,signupsource,state
0,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
1,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
2,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
3,5ff1e1eacfcf6c399c274ae6,True,2021-01-03 15:25:30.554,2021-01-03 15:25:30.597,consumer,Email,WI
4,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
5,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
6,5ff1e1e8cfcf6c399c274ad9,True,2021-01-03 15:25:28.354,2021-01-03 15:25:28.392,consumer,Email,WI
7,5ff1e1b7cfcf6c399c274a5a,True,2021-01-03 15:24:39.626,2021-01-03 15:24:39.665,consumer,Email,WI
8,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
9,5ff1e1f1cfcf6c399c274b0b,True,2021-01-03 15:25:37.564,2021-01-03 15:25:37.599,consumer,Email,WI
10,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
11,5ff1e1eacfcf6c399c274ae6,True,2021-01-03 15:25:30.554,2021-01-03 15:25:30.597,consumer,Email,WI
12,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
13,5ff1e1eacfcf6c399c274ae6,True,2021-01-03 15:25:30.554,2021-01-03 15:25:30.597,consumer,Email,WI
14,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
15,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
16,5ff1e1e4cfcf6c399c274ac3,True,2021-01-03 15:25:24.656,2021-01-03 15:25:24.694,consumer,Email,WI
17,5ff1e1b4cfcf6c399c274a54,True,2021-01-03 15:24:36.410,2021-01-03 15:24:36.452,consumer,Email,WI
18,5ff1e1eacfcf6c399c274ae6,True,2021-01-03 15:25:30.554,2021-01-03 15:25:30.597,consumer,Email,WI
19,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 15:24:04.800,2021-01-03 15:25:37.858,consumer,Email,WI
20,5ff370c562fde912123a5e0e,True,2021-01-04 19:47:17.776,2021-01-04 19:50:50.563,consumer,Email,WI
21,5ff36d0362fde912123a5535,True,2021-01-04 19:31:15.973,2021-01-04 19:34:42.944,consumer,Email,WI
22,5ff36d83135e7011bcb864d6,True,2021-01-04 19:33:23.244,2021-01-04 19:33:23.425,consumer,Email,WI
23,5ff36c8862fde912123a538a,True,2021-01-04 19:29:12.943,2021-01-04 19:29:13.141,consumer,Email,WI
24,5ff370c562fde912123a5e0e,True,2021-01-04 19:47:17.776,2021-01-04 19:50:50.563,consumer,Email,WI
25,5ff36be7135e7011bcb856d3,True,2021-01-04 19:26:31.239,2021-01-04 19:29:52.726,consumer,Email,WI
26,5ff36d0362fde912123a5535,True,2021-01-04 19:31:15.973,2021-01-04 19:34:42.944,consumer,Email,WI
27,5ff36be7135e7011bcb856d3,True,2021-01-04 19:26:31.239,2021-01-04 19:29:52.726,consumer,Email,WI
28,5ff36a3862fde912123a4460,True,2021-01-04 19:19:20.352,2021-01-04 19:23:05.340,consumer,Email,WI
29,5ff36d0362fde912123a5535,True,2021-01-04 19:31:15.973,2021-01-04 19:34:42.944,consumer,Email,WI
...,...,...,...,...,...,...,...
465,5fa41775898c7a11a6bcef3e,True,2020-11-05 15:17:09.396,2021-03-04 16:02:02.026,fetch-staff,Email,NaN
466,5fa41775898c7a11a6bcef3e,True,2020-11-05 15:17:09.396,2021-03-04 16:02:02.026,fetch-staff,Email,NaN
467,5fa41775898c7a11a6bcef3e,True,2020-11-05 15:17:09.396,2021-03-04 16:02:02.026,fetch-staff,Email,NaN
468,5fa41775898c7a11a6bcef3e,True,2020-11-05 15:17:09.396,2021-03-04 16:02:02.026,fetch-staff,Email,NaN
469,5fa41775898c7a11a6bcef3e,True,2020-11-05 15:17:09.396,2021-03-04 16:02:02.026,fetch-staff,Email,NaN
470,5fa41775898c7a11a6bcef3e,True,2020-11-05 15:17:09.396,2021-03-04 16:02:02.026,fetch-staff,Email,NaN
471,5fa41775898c7a11a6bcef3e,True,2020-11-05 15:17:09.396,2021-03-04 16:02:02.026,fetch-staff,Email,NaN
472,5fa41775898c7a11a6bcef3e,True,2020-11-05 15:17:09.396,2021-03-04 16:02:02.026,fetch-staff,Email,NaN
473,5fa41775898c7a11a6bcef3e,True,2020-11-05 15:17:09.396,2021-03-04 16:02:02.026,fetch-staff,Email,NaN
474,5fa41775898c7a11a6bcef3e,True,2020-11-05 15:17:09.396,2021-03-04 16:02:02.026,fetch-staff,Email,NaN
475,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
476,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
477,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
478,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
479,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
480,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
481,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
482,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
483,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
484,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
485,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
486,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
487,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
488,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
489,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
490,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
491,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
492,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
493,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN
494,54943462e4b07e684157a532,True,2014-12-19 14:21:22.381,2021-03-05 16:52:23.204,fetch-staff,NaN,NaN

## Third Dataset (brands)

In [128]:
#Reading the third dataset

brands = pd.read_json('./brands.json', lines = True)
brands

,_id,barcode,brandCode,category,categoryCode,cpg,name,topBrand
0,{'$oid': '601ac115be37ce2ead437551'},511111019862,NaN,Baking,BAKING,"{'$id': {'$oid': '601ac114be37ce2ead437550'}, ...",test brand @1612366101024,0.0
1,{'$oid': '601c5460be37ce2ead43755f'},511111519928,STARBUCKS,Beverages,BEVERAGES,"{'$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}, ...",Starbucks,0.0
2,{'$oid': '601ac142be37ce2ead43755d'},511111819905,TEST BRANDCODE @1612366146176,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146176,0.0
3,{'$oid': '601ac142be37ce2ead43755a'},511111519874,TEST BRANDCODE @1612366146051,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146051,0.0
4,{'$oid': '601ac142be37ce2ead43755e'},511111319917,TEST BRANDCODE @1612366146827,Candy & Sweets,CANDY_AND_SWEETS,"{'$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}, ...",test brand @1612366146827,0.0
5,{'$oid': '601ac142be37ce2ead43755b'},511111719885,TEST BRANDCODE @1612366146091,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146091,0.0
6,{'$oid': '601ac142be37ce2ead43755c'},511111219897,TEST BRANDCODE @1612366146133,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146133,0.0
7,{'$oid': '5cdad0f5166eb33eb7ce0faa'},511111104810,J.L. KRAFT,Condiments & Sauces,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",J.L. Kraft,NaN
8,{'$oid': '5ab15636e4b0be0a89bb0b07'},511111504412,CAMPBELLS HOME STYLE,Canned Goods & Soups,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0...",Campbell's Home Style,0.0
9,{'$oid': '5c408e8bcd244a1fdb47aee7'},511111504788,TEST,Baking,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '59ba6f1ce4b0...",test,NaN
10,{'$oid': '5f4bf556be37ce0b4491554d'},511111516354,TEST BRANDCODE @1598813526777,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f4bf556be37...",test brand @1598813526777,NaN
11,{'$oid': '57c08106e4b0718ff5fcb02c'},511111102540,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b0...",MorningStar,NaN
12,{'$oid': '588ba07be4b02187f85cdadd'},511111201076,CALUMET,Baking,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Calumet,0.0
13,{'$oid': '5d6413156d5f3b23d1bc790a'},511111205012,511111205012,Magazines,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f...",Entertainment Weekly,NaN
14,{'$oid': '585a9611e4b03e62d1ce0e74'},511111801801,AUNT JEMIMA SYRUP,Breakfast & Cereal,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b0...",AUNT JEMIMA Syrup,0.0
15,{'$oid': '57e5820ce4b0ac389136a311'},511111202233,MOLSON,Beer Wine Spirits,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f709e4b0...",Molson Canadian,0.0
16,{'$oid': '5fb6adb8be37ce522e165cb8'},511111817376,LOTRIMIN,Health & Wellness,HEALTHY_AND_WELLNESS,"{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda...",LotriminÂ®,0.0
17,{'$oid': '5f358338be37ce443bf9d55a'},511111515319,TEST BRANDCODE @1597342520277,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f358338be37...",test brand @1597342520277,NaN
18,{'$oid': '5fb28549be37ce522e165cb5'},511111317364,NaN,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5fb28549be37...",test brand @1605535049181,0.0
19,{'$oid': '592486bfe410d61fcea3d139'},511111300700,ST IVES,Beauty,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b0...",ST. IVES,0.0
20,{'$oid': '5c4699f387ff3577e203ea29'},511111305125,CHRISIMAGE,Baby,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '55b62995e4b0...",Chris Image Test,NaN
21,{'$oid': '5da6071ea60b87376833e34d'},511111005650,ALKA SELTZER,Health & Wellness,HEALTHY_AND_WELLNESS,"{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda...",Alka-SeltzerÂ®,NaN
22,{'$oid': '57ebc011e4b0ac389136a335'},511111802129,JACK DANIEL'S BARBECUE,Condiments & Sauces,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Jack Daniel's,0.0
23,{'$oid': '5332f5fee4b03c9a25efd0bd'},511111303947,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '53e10d6368ab...",Bottled Starbucks,NaN
24,{'$oid': '5332fa7ce4b03c9a25efd22e'},511111802914,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b0...",Full Throttle,NaN
25,{'$oid': '5e9f18bfbe37ce3e45b6a77f'},511111914549,NaN,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5e9f12f5be37...",PopUp Brand A,NaN
26,{'$oid': '592486bee410d61fcea3d133'},511111400769,MAGNUM Ice Cream,Frozen,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b0...",MAGNUM Ice Cream,0.0
27,{'$oid': '5d66d71fa3a018093ab34728'},511111105329,511111105329,Magazines,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f...",Elegant Homes Magazine,NaN
28,{'$oid': '5f493e72be37ce64d0ae36c6'},511111316114,TEST BRANDCODE @1598635634882,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f493e72be37...",test brand @1598635634882,NaN
29,{'$oid': '5f4936ddbe37ce52f8314fd9'},511111315957,NaN,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f4936dcbe37...",test brand @1598633693011,NaN
...,...,...,...,...,...,...,...,...
1137,{'$oid': '57ebbfa9e4b0ac389136a331'},511111202165,,Beverages,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Gevalia Iced Coffee,0.0
1138,{'$oid': '5a5d2c59e4b06ba572cf24a9'},511111900054,SUNSILK,Beauty & Personal Care,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368ab...",Sunsilk,NaN
1139,{'$oid': '5887a051e4b02187f85cdad0'},511111401209,BAKER'S,Baking,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Baker's,0.0
1140,{'$oid': '5ab1528ce4b0915382df761c'},511111504344,ECCE PANIS,Grocery,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0...",Ecce Panis,0.0
1141,{'$oid': '5d66d6016d5f3b6188d4f047'},511111405306,511111405306,Magazines,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f...",Do It Yourself Special Edition Magazine,NaN
1142,{'$oid': '5f21c54abe37ce7958c59528'},511111315230,AIR WICK,Cleaning & Home Improvement,CLEANING_AND_HOME_IMPROVEMENT,"{'$ref': 'Cogs', '$id': {'$oid': '5f10c05cbe37...",AIR WICKÂ®,0.0
1143,{'$oid': '5332f7fde4b03c9a25efd168'},511111903345,HAMM'S,Beer Wine Spirits,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f709e4b0...",Hamm's Beer,0.0
1144,{'$oid': '57c08242e4b0718ff5fcb032'},511111202516,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b0...",Corona,NaN
1145,{'$oid': '5f5bc4f1be37ce17125ac0e9'},511111716594,TEST BRANDCODE @1599849713740,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f5bc4f1be37...",test brand @1599849713740,NaN
1146,{'$oid': '5332fa12e4b03c9a25efd1e6'},511111703105,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332fa12e4b0...",Bellatoria,NaN
1147,{'$oid': '5dc0351a1dda2c0ad7da64aa'},511111306238,MONSTERS CEREAL,Breakfast & Cereal,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b0...",Monster's Cereal,NaN
1148,{'$oid': '5d66e2d46d5f3b6188d4f056'},511111905523,TAZO BOTTLED TEAS,Beverages,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b0...",Tazo Bottled Teas,NaN
1149,{'$oid': '5a0219ede4b00d6a5ccb394e'},511111400554,TONI&GUY,Personal Care,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b0...",TONI&GUY,0.0
1150,{'$oid': '5d66da306d5f3b6188d4f04c'},511111005377,511111005377,Magazines,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f...",Modern Farmhouse Magazine,NaN
1151,{'$oid': '5d66dfe6a3a018093ab3472c'},511111905479,511111905479,Magazines,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f...",Weight Watchers Special Edition Magazine,NaN
1152,{'$oid': '5f3e9172be37ce5a0e01b955'},511111715559,TEST BRANDCODE @1597935986434,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f3e9172be37...",test brand @1597935986434,NaN
1153,{'$oid': '58b598dbe4b0857c2ddb7253'},511111101017,MICKEY'S,Beer Wine Spirits,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b0...",Mickey's,0.0
1154,{'$oid': '57d95826e4b0ac389136a2b7'},511111302346,CRYSTAL LIGHT,Beverages,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Crystal Light,0.0
1155,{'$oid': '5a5d1bffe4b0db471c2d0423'},511111000396,COORS EXTRA GOLD,Beer Wine Spirits,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b0...",Coors Extra Gold,NaN
1156,{'$oid': '5fb82fe3be37ce522e165cea'},511111617853,D ITALIANO,Grocery,GROCERY,"{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37...",D'Italiano,0.0
1157,{'$oid': '5332fa75e4b03c9a25efd221'},511111303015,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b0...",DASANI,NaN
1158,{'$oid': '5f628215be37ce78e6e2efab'},511111716648,TEST BRANDCODE @1600291349043,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f628214be37...",test brand @1600291349042,NaN
1159,{'$oid': '585a96cbe4b03e62d1ce0e88'},511111501619,,Beverages,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b0...",Pepsi Max,0.0
1160,{'$oid': '5887a216e4b02187f85cdad5'},511111401155,CLAUSSEN,Deli,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Claussen,0.0
1161,{'$oid': '5332f709e4b03c9a25efd0f2'},511111403845,BLUE MOON,Beer Wine Spirits,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b0...",Blue Moon,0.0
1162,{'$oid': '5f77274dbe37ce6b592e90c0'},511111116752,NaN,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f77274dbe37...",test brand @1601644365844,NaN
1163,{'$oid': '5dc1fca91dda2c0ad7da64ae'},511111706328,DIPPIN DOTS CEREAL,Breakfast & Cereal,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368ab...",Dippin DotsÂ® Cereal,NaN
1164,{'$oid': '5f494c6e04db711dd8fe87e7'},511111416173,TEST BRANDCODE @1598639215217,Candy & Sweets,CANDY_AND_SWEETS,"{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b0...",test brand @1598639215217,NaN
1165,{'$oid': '5a021611e4b00efe02b02a57'},511111400608,LIPTON TEA Leaves,Grocery,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b0...",LIPTON TEA Leaves,0.0
1166,{'$oid': '6026d757be37ce6369301468'},511111019930,TEST BRANDCODE @1613158231644,Baking,BAKING,"{'$id': {'$oid': '6026d757be37ce6369301467'}, ...",test brand @1613158231643,0.0

In [136]:
#In the cpg column, I observed that there is an "oid" inside dictionary. 
#I wanted to check if this is same as "_id" in receipts data set
#I wanted to check if this is same as "_id" in users data set

new = brands['cpg']

oid = set()
for i, d in new.iteritems():
    oid.add(d['$id']['$oid'])

oid

{'5332f5ebe4b03c9a25efd0a8',
 '5332f5f2e4b03c9a25efd0aa',
 '5332f5f3e4b03c9a25efd0ac',
 '5332f5f3e4b03c9a25efd0ae',
 '5332f5f6e4b03c9a25efd0b4',
 '5332f5fbe4b03c9a25efd0ba',
 '5332f6ede4b03c9a25efd0e6',
 '5332f709e4b03c9a25efd0f1',
 '5332f712e4b03c9a25efd0f9',
 '5332f734e4b03c9a25efd104',
 '5332f7a7e4b03c9a25efd134',
 '5332f7ffe4b03c9a25efd16b',
 '5332fa12e4b03c9a25efd1e7',
 '5332fa58e4b03c9a25efd215',
 '53501d2ab9237fd7718f9e18',
 '53501d2ab9237fd7718f9e1a',
 '537b7ec2892471241348d709',
 '53e10d6368abd3c7065097cc',
 '540f215de4b09fb9af4b49f1',
 '5459429be4b0bfcb1e864082',
 '550b2565e4b001d5e9e4146f',
 '559c2234e4b06aca36af13c6',
 '55a41a91e4b0d0a65b3692ec',
 '55a41b4be4b0d0a65b3692ee',
 '55a58719e4b0d0a65b3693cc',
 '55b62995e4b0d8e685c14213',
 '56462469e4b0c05761111936',
 '57ace90fe4b057c992a316ab',
 '581ce8d5e4b058c71f74c442',
 '59b96571e4b0bf7c7980588b',
 '59ba6f1ce4b092b29c167346',
 '5a734034e4b0d58f376be874',
 '5c45f8b087ff3552f950f026',
 '5c4f20b01b4181298aacffc1',
 '5c6c2ee995144c6db8fe1976',
 '5c6d516795144c607914426e',
 '5c7470c895144c124ecd5c09',
 '5c76d20595144c5375687b4e',
 '5c76dd1095144c5375687b51',
 '5d5d4fd16d5f3b23d1bc7905',
 '5d66b9dcee7f2d201c7281cd',
 '5d9b4f591dda2c6225a284aa',
 '5e28b81cee7f2d697e835bcd',
 '5e5ea9cc9c50da1291a6d074',
 '5e7cf838f221c312e698a628',
 '5e9f12f5be37ce3e45b6a77e',
 '5ea07defbe37ce3e45b6a780',
 '5eebc5412455c97a877ef382',
 '5f036ccc2455c947fde9362f',
 '5f10c05cbe37ce238c6cabaf',
 '5f16f512be37ce2b30061e1d',
 '5f16f535be37ce2b30061e24',
 '5f19e054be37ce33f74a166e',
 '5f19e062be37ce33f74a1674',
 '5f208daebe37ce7958c59520',
 '5f208db0be37ce7958c59526',
 '5f358338be37ce443bf9d557',
 '5f35834dbe37ce443bf9d564',
 '5f35a0babe37ce6853cff1fd',
 '5f35a0bcbe37ce6853cff20a',
 '5f38576ebe37ce5178517aca',
 '5f38578fbe37ce5178517ad3',
 '5f3d6f43be37ce4ddbb1bb38',
 '5f3d6f44be37ce4ddbb1bb3a',
 '5f3e9172be37ce5a0e01b952',
 '5f3e9195be37ce5a0e01b95f',
 '5f3ff200be37ce1c81aa1e0a',
 '5f3ff222be37ce1c81aa1e0c',
 '5f403231be37ce5f78d9ed14',
 '5f403232be37ce5f78d9ed1a',
 '5f43faabbe37ce3ef3fd3714',
 '5f43faadbe37ce3ef3fd371a',
 '5f441280be37ce5dbe9b7c7d',
 '5f441281be37ce5dbe9b7c83',
 '5f4802bdbe37ce0c8303373c',
 '5f4802d2be37ce0c83033742',
 '5f493665be37ce52f8314fc9',
 '5f493682be37ce52f8314fcb',
 '5f4936dcbe37ce52f8314fd8',
 '5f4936ddbe37ce52f8314fda',
 '5f493d85be37ce64d0ae36b1',
 '5f493dabbe37ce64d0ae36ba',
 '5f493e72be37ce64d0ae36c0',
 '5f493e72be37ce64d0ae36c2',
 '5f494c5d04db711dd8fe87e2',
 '5f494cf904db711dd8fe87ef',
 '5f4a64e7be37ce17d23b3178',
 '5f4a650bbe37ce17d23b317e',
 '5f4a7a5bbe37ce2d95e65c9f',
 '5f4a7a60be37ce2d95e65cac',
 '5f4bf53dbe37ce0b44915540',
 '5f4bf556be37ce0b44915549',
 '5f4cff1aa475f1050a66b566',
 '5f4cffbaa475f1050a66b573',
 '5f504ac2be37ce0b793c9411',
 '5f504acabe37ce0b793c9417',
 '5f513e9ebe37ce21f1287bff',
 '5f513ea0be37ce21f1287c01',
 '5f58fa84be37ce21f1287c0f',
 '5f5bc4f1be37ce17125ac0e6',
 '5f5bc4f1be37ce17125ac0e8',
 '5f628214be37ce78e6e2efaa',
 '5f628235be37ce78e6e2efb0',
 '5f77274bbe37ce6b592e90b9',
 '5f77274dbe37ce6b592e90bf',
 '5f772951be37ce6b592e90cf',
 '5f772951be37ce6b592e90d1',
 '5f7760f0be37ce1d26d7b7a2',
 '5f7760ffbe37ce1d26d7b7a8',
 '5f7ba644be37ce23081c5289',
 '5f7ba678be37ce23081c5296',
 '5f7ba914be37ce2f290fb24f',
 '5f7ba932be37ce2f290fb251',
 '5f872b7fbe37ce66db5dd975',
 '5f872bd3be37ce66db5dd982',
 '5f9770bfbe37ce03d08a2d83',
 '5f9770c0be37ce03d08a2d89',
 '5f99f71bbe37ce13da9eade6',
 '5f99f720be37ce13da9eadec',
 '5fa1c567be37ce402c4618ef',
 '5fa1c568be37ce402c4618f5',
 '5fa98944be37ce239d1070fd',
 '5fa98944be37ce239d1070ff',
 '5fb2852cbe37ce522e165cae',
 '5fb28549be37ce522e165cb4',
 '5fb6b608be37ce522e165cb9',
 '5fb6d381be37ce522e165cbd',
 '5fc54c0abe37ce1911dbb3b1',
 '5fc54c17be37ce1911dbb3b7',
 '5fcda47cbe37ce688e08b0c2',
 '5fcda494be37ce688e08b0cb',
 '5fcff304be37ce6d53dfc683',
 '5fcff319be37ce6d53dfc690',
 '5fd29590be37ce38bbbefb25',
 '5fd29591be37ce38bbbefb2b',
 '5fd2a0aebe37ce49eb72c0ed',
 '5fd2a0bfbe37ce49eb72c0ef',
 '5fd3acb5be37ce0d9386bb3e',
 '5fd3acb9be37ce0d9386bb4b',
 '5fd3ae1fbe37ce0d9386bb54',
 '5fd3ae20be37ce0d9386bb5a',
 '5fd7f2b3be37ce7339755868',
 '5fd7f2b8be37ce733975586e',
 '5fda3711be37ce09e351596d',
 '5fda3724be37ce09e351596f',
 '5fdce8dabe37ce5fa8ba59be',
 '5fdce8edbe37ce5fa8ba59cb',
 '5fdce9cabe37ce5fa8ba59cd',
 '5fdce9e9be37ce5fa8ba59d6',
 '5ff3842abe37ce2c56dacbab',
 '5ff3842bbe37ce2c56dacbad',
 '5ff73cf9be37ce1e961f3256',
 '5ff73cffbe37ce1e961f325c',
 '5ff74123be37ce1e961f3265',
 '5ff74126be37ce1e961f326e',
 '5ff744ffbe37ce1e961f3274',
 '5ff74500be37ce1e961f3276',
 '5ff75cdebe37ce1e961f328a',
 '5ff75cdebe37ce1e961f328c',
 '5ff768d4be37ce1e961f3299',
 '5ff768e3be37ce1e961f329f',
 '5ff77857be37ce58ce500839',
 '5ff77859be37ce58ce50083f',
 '5ff78070be37ce6a424ca0e5',
 '5ff78071be37ce6a424ca0e7',
 '5ff789c5be37ce786ba0f6a2',
 '5ff789d5be37ce786ba0f6a8',
 '5ff8b5fbbe37ce4a1398660d',
 '5ff8b5febe37ce4a13986613',
 '5ffe2ca0be37ce5e01754c09',
 '5ffe2ce0be37ce5e01754c16',
 '5ffe2df8be37ce5e01754c1f',
 '5ffe2e38be37ce5e01754c21',
 '5ffe336ebe37ce5e01754c2e',
 '5ffe3381be37ce5e01754c34',
 '5ffe347ebe37ce5e01754c3d',
 '5ffe3480be37ce5e01754c43',
 '5ffe35eabe37ce5e01754c45',
 '5ffe35f9be37ce5e01754c4b',
 '5ffe3681be37ce5e01754c54',
 '5ffe3686be37ce5e01754c5d',
 '5ffe3a85be37ce7aab2d4fd4',
 '5ffe3a87be37ce7aab2d4fda',
 '5fff3a7abe37ce2bb793010d',
 '5fff3aa0be37ce2bb7930116',
 '6000a0c6be37ce2bb793011c',
 '6000a0f3be37ce2bb7930129',
 '6000b8c3be37ce321363c6bf',
 '6000b8c4be37ce321363c6c5',
 '60019b82be37ce4f17e558d1',
 '60019b83be37ce4f17e558d7',
 '60074260be37ce360be639f5',
 '60074277be37ce360be639fe',
 '601ac114be37ce2ead437550',
 '601ac142be37ce2ead437559',
 '6026d757be37ce6369301467'}

In [138]:
(oid).intersection(set(receipts['_id'])) 

#There is no common output which means both the column are different from receipts and brands dataset

set()

In [139]:
(oid).intersection(set(users['_id'])) 

#There is no common output which means both the column are different from receipts and users dataset

set()

In [140]:
#Above was a test to check if there was an intersecting between the values in the cpg column and the other tables 
#But no relationship was established and also there was no clear understanding of the cpg column and its use in further analysis
#Therefore dropping the column

In [129]:
brands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1167 entries, 0 to 1166
Data columns (total 8 columns):
_id             1167 non-null object
barcode         1167 non-null int64
brandCode       933 non-null object
category        1012 non-null object
categoryCode    517 non-null object
cpg             1167 non-null object
name            1167 non-null object
topBrand        555 non-null float64
dtypes: float64(1), int64(1), object(6)
memory usage: 73.0+ KB

In [130]:
#Making all the column names in lower case in order to write sql query
brands.columns= brands.columns.str.lower()

In [131]:
#Using the "clean_id" function to clean the _id in brands dataset
brands['_id'] = clean_id(brands['_id'],brands)

In [132]:
brands

,_id,barcode,brandcode,category,categorycode,cpg,name,topbrand
0,601ac115be37ce2ead437551,511111019862,NaN,Baking,BAKING,"{'$id': {'$oid': '601ac114be37ce2ead437550'}, ...",test brand @1612366101024,0.0
1,601c5460be37ce2ead43755f,511111519928,STARBUCKS,Beverages,BEVERAGES,"{'$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}, ...",Starbucks,0.0
2,601ac142be37ce2ead43755d,511111819905,TEST BRANDCODE @1612366146176,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146176,0.0
3,601ac142be37ce2ead43755a,511111519874,TEST BRANDCODE @1612366146051,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146051,0.0
4,601ac142be37ce2ead43755e,511111319917,TEST BRANDCODE @1612366146827,Candy & Sweets,CANDY_AND_SWEETS,"{'$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}, ...",test brand @1612366146827,0.0
5,601ac142be37ce2ead43755b,511111719885,TEST BRANDCODE @1612366146091,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146091,0.0
6,601ac142be37ce2ead43755c,511111219897,TEST BRANDCODE @1612366146133,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146133,0.0
7,5cdad0f5166eb33eb7ce0faa,511111104810,J.L. KRAFT,Condiments & Sauces,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",J.L. Kraft,NaN
8,5ab15636e4b0be0a89bb0b07,511111504412,CAMPBELLS HOME STYLE,Canned Goods & Soups,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0...",Campbell's Home Style,0.0
9,5c408e8bcd244a1fdb47aee7,511111504788,TEST,Baking,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '59ba6f1ce4b0...",test,NaN
10,5f4bf556be37ce0b4491554d,511111516354,TEST BRANDCODE @1598813526777,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f4bf556be37...",test brand @1598813526777,NaN
11,57c08106e4b0718ff5fcb02c,511111102540,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b0...",MorningStar,NaN
12,588ba07be4b02187f85cdadd,511111201076,CALUMET,Baking,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Calumet,0.0
13,5d6413156d5f3b23d1bc790a,511111205012,511111205012,Magazines,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f...",Entertainment Weekly,NaN
14,585a9611e4b03e62d1ce0e74,511111801801,AUNT JEMIMA SYRUP,Breakfast & Cereal,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b0...",AUNT JEMIMA Syrup,0.0
15,57e5820ce4b0ac389136a311,511111202233,MOLSON,Beer Wine Spirits,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f709e4b0...",Molson Canadian,0.0
16,5fb6adb8be37ce522e165cb8,511111817376,LOTRIMIN,Health & Wellness,HEALTHY_AND_WELLNESS,"{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda...",LotriminÂ®,0.0
17,5f358338be37ce443bf9d55a,511111515319,TEST BRANDCODE @1597342520277,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f358338be37...",test brand @1597342520277,NaN
18,5fb28549be37ce522e165cb5,511111317364,NaN,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5fb28549be37...",test brand @1605535049181,0.0
19,592486bfe410d61fcea3d139,511111300700,ST IVES,Beauty,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b0...",ST. IVES,0.0
20,5c4699f387ff3577e203ea29,511111305125,CHRISIMAGE,Baby,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '55b62995e4b0...",Chris Image Test,NaN
21,5da6071ea60b87376833e34d,511111005650,ALKA SELTZER,Health & Wellness,HEALTHY_AND_WELLNESS,"{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda...",Alka-SeltzerÂ®,NaN
22,57ebc011e4b0ac389136a335,511111802129,JACK DANIEL'S BARBECUE,Condiments & Sauces,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Jack Daniel's,0.0
23,5332f5fee4b03c9a25efd0bd,511111303947,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '53e10d6368ab...",Bottled Starbucks,NaN
24,5332fa7ce4b03c9a25efd22e,511111802914,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b0...",Full Throttle,NaN
25,5e9f18bfbe37ce3e45b6a77f,511111914549,NaN,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5e9f12f5be37...",PopUp Brand A,NaN
26,592486bee410d61fcea3d133,511111400769,MAGNUM Ice Cream,Frozen,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b0...",MAGNUM Ice Cream,0.0
27,5d66d71fa3a018093ab34728,511111105329,511111105329,Magazines,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f...",Elegant Homes Magazine,NaN
28,5f493e72be37ce64d0ae36c6,511111316114,TEST BRANDCODE @1598635634882,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f493e72be37...",test brand @1598635634882,NaN
29,5f4936ddbe37ce52f8314fd9,511111315957,NaN,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f4936dcbe37...",test brand @1598633693011,NaN
...,...,...,...,...,...,...,...,...
1137,57ebbfa9e4b0ac389136a331,511111202165,,Beverages,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Gevalia Iced Coffee,0.0
1138,5a5d2c59e4b06ba572cf24a9,511111900054,SUNSILK,Beauty & Personal Care,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368ab...",Sunsilk,NaN
1139,5887a051e4b02187f85cdad0,511111401209,BAKER'S,Baking,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Baker's,0.0
1140,5ab1528ce4b0915382df761c,511111504344,ECCE PANIS,Grocery,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0...",Ecce Panis,0.0
1141,5d66d6016d5f3b6188d4f047,511111405306,511111405306,Magazines,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f...",Do It Yourself Special Edition Magazine,NaN
1142,5f21c54abe37ce7958c59528,511111315230,AIR WICK,Cleaning & Home Improvement,CLEANING_AND_HOME_IMPROVEMENT,"{'$ref': 'Cogs', '$id': {'$oid': '5f10c05cbe37...",AIR WICKÂ®,0.0
1143,5332f7fde4b03c9a25efd168,511111903345,HAMM'S,Beer Wine Spirits,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f709e4b0...",Hamm's Beer,0.0
1144,57c08242e4b0718ff5fcb032,511111202516,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b0...",Corona,NaN
1145,5f5bc4f1be37ce17125ac0e9,511111716594,TEST BRANDCODE @1599849713740,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f5bc4f1be37...",test brand @1599849713740,NaN
1146,5332fa12e4b03c9a25efd1e6,511111703105,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332fa12e4b0...",Bellatoria,NaN
1147,5dc0351a1dda2c0ad7da64aa,511111306238,MONSTERS CEREAL,Breakfast & Cereal,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b0...",Monster's Cereal,NaN
1148,5d66e2d46d5f3b6188d4f056,511111905523,TAZO BOTTLED TEAS,Beverages,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b0...",Tazo Bottled Teas,NaN
1149,5a0219ede4b00d6a5ccb394e,511111400554,TONI&GUY,Personal Care,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b0...",TONI&GUY,0.0
1150,5d66da306d5f3b6188d4f04c,511111005377,511111005377,Magazines,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f...",Modern Farmhouse Magazine,NaN
1151,5d66dfe6a3a018093ab3472c,511111905479,511111905479,Magazines,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f...",Weight Watchers Special Edition Magazine,NaN
1152,5f3e9172be37ce5a0e01b955,511111715559,TEST BRANDCODE @1597935986434,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f3e9172be37...",test brand @1597935986434,NaN
1153,58b598dbe4b0857c2ddb7253,511111101017,MICKEY'S,Beer Wine Spirits,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b0...",Mickey's,0.0
1154,57d95826e4b0ac389136a2b7,511111302346,CRYSTAL LIGHT,Beverages,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Crystal Light,0.0
1155,5a5d1bffe4b0db471c2d0423,511111000396,COORS EXTRA GOLD,Beer Wine Spirits,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b0...",Coors Extra Gold,NaN
1156,5fb82fe3be37ce522e165cea,511111617853,D ITALIANO,Grocery,GROCERY,"{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37...",D'Italiano,0.0
1157,5332fa75e4b03c9a25efd221,511111303015,NaN,NaN,NaN,"{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b0...",DASANI,NaN
1158,5f628215be37ce78e6e2efab,511111716648,TEST BRANDCODE @1600291349043,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f628214be37...",test brand @1600291349042,NaN
1159,585a96cbe4b03e62d1ce0e88,511111501619,,Beverages,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b0...",Pepsi Max,0.0
1160,5887a216e4b02187f85cdad5,511111401155,CLAUSSEN,Deli,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b0...",Claussen,0.0
1161,5332f709e4b03c9a25efd0f2,511111403845,BLUE MOON,Beer Wine Spirits,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b0...",Blue Moon,0.0
1162,5f77274dbe37ce6b592e90c0,511111116752,NaN,Baking,BAKING,"{'$ref': 'Cogs', '$id': {'$oid': '5f77274dbe37...",test brand @1601644365844,NaN
1163,5dc1fca91dda2c0ad7da64ae,511111706328,DIPPIN DOTS CEREAL,Breakfast & Cereal,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368ab...",Dippin DotsÂ® Cereal,NaN
1164,5f494c6e04db711dd8fe87e7,511111416173,TEST BRANDCODE @1598639215217,Candy & Sweets,CANDY_AND_SWEETS,"{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b0...",test brand @1598639215217,NaN
1165,5a021611e4b00efe02b02a57,511111400608,LIPTON TEA Leaves,Grocery,NaN,"{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b0...",LIPTON TEA Leaves,0.0
1166,6026d757be37ce6369301468,511111019930,TEST BRANDCODE @1613158231644,Baking,BAKING,"{'$id': {'$oid': '6026d757be37ce6369301467'}, ...",test brand @1613158231643,0.0

In [86]:
brands.drop('cpg', inplace = True, axis = 1) #Dropping the cpg column

In [87]:
brands #Cleaned brands dataset

,_id,barcode,brandcode,category,categorycode,name,topbrand
0,601ac115be37ce2ead437551,511111019862,NaN,Baking,BAKING,test brand @1612366101024,0.0
1,601c5460be37ce2ead43755f,511111519928,STARBUCKS,Beverages,BEVERAGES,Starbucks,0.0
2,601ac142be37ce2ead43755d,511111819905,TEST BRANDCODE @1612366146176,Baking,BAKING,test brand @1612366146176,0.0
3,601ac142be37ce2ead43755a,511111519874,TEST BRANDCODE @1612366146051,Baking,BAKING,test brand @1612366146051,0.0
4,601ac142be37ce2ead43755e,511111319917,TEST BRANDCODE @1612366146827,Candy & Sweets,CANDY_AND_SWEETS,test brand @1612366146827,0.0
5,601ac142be37ce2ead43755b,511111719885,TEST BRANDCODE @1612366146091,Baking,BAKING,test brand @1612366146091,0.0
6,601ac142be37ce2ead43755c,511111219897,TEST BRANDCODE @1612366146133,Baking,BAKING,test brand @1612366146133,0.0
7,5cdad0f5166eb33eb7ce0faa,511111104810,J.L. KRAFT,Condiments & Sauces,NaN,J.L. Kraft,NaN
8,5ab15636e4b0be0a89bb0b07,511111504412,CAMPBELLS HOME STYLE,Canned Goods & Soups,NaN,Campbell's Home Style,0.0
9,5c408e8bcd244a1fdb47aee7,511111504788,TEST,Baking,NaN,test,NaN
10,5f4bf556be37ce0b4491554d,511111516354,TEST BRANDCODE @1598813526777,Baking,BAKING,test brand @1598813526777,NaN
11,57c08106e4b0718ff5fcb02c,511111102540,NaN,NaN,NaN,MorningStar,NaN
12,588ba07be4b02187f85cdadd,511111201076,CALUMET,Baking,NaN,Calumet,0.0
13,5d6413156d5f3b23d1bc790a,511111205012,511111205012,Magazines,NaN,Entertainment Weekly,NaN
14,585a9611e4b03e62d1ce0e74,511111801801,AUNT JEMIMA SYRUP,Breakfast & Cereal,NaN,AUNT JEMIMA Syrup,0.0
15,57e5820ce4b0ac389136a311,511111202233,MOLSON,Beer Wine Spirits,NaN,Molson Canadian,0.0
16,5fb6adb8be37ce522e165cb8,511111817376,LOTRIMIN,Health & Wellness,HEALTHY_AND_WELLNESS,LotriminÂ®,0.0
17,5f358338be37ce443bf9d55a,511111515319,TEST BRANDCODE @1597342520277,Baking,BAKING,test brand @1597342520277,NaN
18,5fb28549be37ce522e165cb5,511111317364,NaN,Baking,BAKING,test brand @1605535049181,0.0
19,592486bfe410d61fcea3d139,511111300700,ST IVES,Beauty,NaN,ST. IVES,0.0
20,5c4699f387ff3577e203ea29,511111305125,CHRISIMAGE,Baby,NaN,Chris Image Test,NaN
21,5da6071ea60b87376833e34d,511111005650,ALKA SELTZER,Health & Wellness,HEALTHY_AND_WELLNESS,Alka-SeltzerÂ®,NaN
22,57ebc011e4b0ac389136a335,511111802129,JACK DANIEL'S BARBECUE,Condiments & Sauces,NaN,Jack Daniel's,0.0
23,5332f5fee4b03c9a25efd0bd,511111303947,NaN,NaN,NaN,Bottled Starbucks,NaN
24,5332fa7ce4b03c9a25efd22e,511111802914,NaN,NaN,NaN,Full Throttle,NaN
25,5e9f18bfbe37ce3e45b6a77f,511111914549,NaN,Baking,BAKING,PopUp Brand A,NaN
26,592486bee410d61fcea3d133,511111400769,MAGNUM Ice Cream,Frozen,NaN,MAGNUM Ice Cream,0.0
27,5d66d71fa3a018093ab34728,511111105329,511111105329,Magazines,NaN,Elegant Homes Magazine,NaN
28,5f493e72be37ce64d0ae36c6,511111316114,TEST BRANDCODE @1598635634882,Baking,BAKING,test brand @1598635634882,NaN
29,5f4936ddbe37ce52f8314fd9,511111315957,NaN,Baking,BAKING,test brand @1598633693011,NaN
...,...,...,...,...,...,...,...
1137,57ebbfa9e4b0ac389136a331,511111202165,,Beverages,NaN,Gevalia Iced Coffee,0.0
1138,5a5d2c59e4b06ba572cf24a9,511111900054,SUNSILK,Beauty & Personal Care,NaN,Sunsilk,NaN
1139,5887a051e4b02187f85cdad0,511111401209,BAKER'S,Baking,NaN,Baker's,0.0
1140,5ab1528ce4b0915382df761c,511111504344,ECCE PANIS,Grocery,NaN,Ecce Panis,0.0
1141,5d66d6016d5f3b6188d4f047,511111405306,511111405306,Magazines,NaN,Do It Yourself Special Edition Magazine,NaN
1142,5f21c54abe37ce7958c59528,511111315230,AIR WICK,Cleaning & Home Improvement,CLEANING_AND_HOME_IMPROVEMENT,AIR WICKÂ®,0.0
1143,5332f7fde4b03c9a25efd168,511111903345,HAMM'S,Beer Wine Spirits,NaN,Hamm's Beer,0.0
1144,57c08242e4b0718ff5fcb032,511111202516,NaN,NaN,NaN,Corona,NaN
1145,5f5bc4f1be37ce17125ac0e9,511111716594,TEST BRANDCODE @1599849713740,Baking,BAKING,test brand @1599849713740,NaN
1146,5332fa12e4b03c9a25efd1e6,511111703105,NaN,NaN,NaN,Bellatoria,NaN
1147,5dc0351a1dda2c0ad7da64aa,511111306238,MONSTERS CEREAL,Breakfast & Cereal,NaN,Monster's Cereal,NaN
1148,5d66e2d46d5f3b6188d4f056,511111905523,TAZO BOTTLED TEAS,Beverages,NaN,Tazo Bottled Teas,NaN
1149,5a0219ede4b00d6a5ccb394e,511111400554,TONI&GUY,Personal Care,NaN,TONI&GUY,0.0
1150,5d66da306d5f3b6188d4f04c,511111005377,511111005377,Magazines,NaN,Modern Farmhouse Magazine,NaN
1151,5d66dfe6a3a018093ab3472c,511111905479,511111905479,Magazines,NaN,Weight Watchers Special Edition Magazine,NaN
1152,5f3e9172be37ce5a0e01b955,511111715559,TEST BRANDCODE @1597935986434,Baking,BAKING,test brand @1597935986434,NaN
1153,58b598dbe4b0857c2ddb7253,511111101017,MICKEY'S,Beer Wine Spirits,NaN,Mickey's,0.0
1154,57d95826e4b0ac389136a2b7,511111302346,CRYSTAL LIGHT,Beverages,NaN,Crystal Light,0.0
1155,5a5d1bffe4b0db471c2d0423,511111000396,COORS EXTRA GOLD,Beer Wine Spirits,NaN,Coors Extra Gold,NaN
1156,5fb82fe3be37ce522e165cea,511111617853,D ITALIANO,Grocery,GROCERY,D'Italiano,0.0
1157,5332fa75e4b03c9a25efd221,511111303015,NaN,NaN,NaN,DASANI,NaN
1158,5f628215be37ce78e6e2efab,511111716648,TEST BRANDCODE @1600291349043,Baking,BAKING,test brand @1600291349042,NaN
1159,585a96cbe4b03e62d1ce0e88,511111501619,,Beverages,NaN,Pepsi Max,0.0
1160,5887a216e4b02187f85cdad5,511111401155,CLAUSSEN,Deli,NaN,Claussen,0.0
1161,5332f709e4b03c9a25efd0f2,511111403845,BLUE MOON,Beer Wine Spirits,NaN,Blue Moon,0.0
1162,5f77274dbe37ce6b592e90c0,511111116752,NaN,Baking,BAKING,test brand @1601644365844,NaN
1163,5dc1fca91dda2c0ad7da64ae,511111706328,DIPPIN DOTS CEREAL,Breakfast & Cereal,NaN,Dippin DotsÂ® Cereal,NaN
1164,5f494c6e04db711dd8fe87e7,511111416173,TEST BRANDCODE @1598639215217,Candy & Sweets,CANDY_AND_SWEETS,test brand @1598639215217,NaN
1165,5a021611e4b00efe02b02a57,511111400608,LIPTON TEA Leaves,Grocery,NaN,LIPTON TEA Leaves,0.0
1166,6026d757be37ce6369301468,511111019930,TEST BRANDCODE @1613158231644,Baking,BAKING,test brand @1613158231643,0.0

## creating a postgres database and inserting tables

In [88]:
#Connecting my jupyter notebook to postgres database. I have created a new database name as 'fetch_rewards' in postgres
#(I have attached screenshot of my cmd window)

conn = psycopg2.connect(
    host="localhost",
    database="fetch_rewards",
    user="postgres",
    password="anuj13")

In [89]:
conn.autocommit = True
cursor = conn.cursor()

In [90]:
cursor.execute("SELECT VERSION();")
version = cursor.fetchone()
print("Connected to - ", version)

Connected to -  ('PostgreSQL 13.3, compiled by Visual C++ build 1914, 64-bit',)

In [91]:
#Created an engine using sqlalchemy in order to load data into my databse in postgres

engine  = sqlalchemy.create_engine('postgresql://postgres:anuj13@localhost:5432/fetch_rewards')

In [92]:
#Loading my 4 tables into database. 

receipts.to_sql('receipts', engine)
rewards_receipt.to_sql('rewards_receipt',engine)
users.to_sql('users', engine)
brands.to_sql('brands', engine)

ValueError: Table 'receipts' already exists.

## Till here I have cleaned all 4 dataset, created a database in postgres and loaded all the clean data to the "fetch_rewards" database. Now we have a clean database from where we can write sql query and get answers to the business questions

## Q) When considering average spend from receipts with 'rewardsReceiptStatus’ of ‘Accepted’ or ‘Rejected’, which is greater?

In [93]:
count = '''(select rewardsreceiptstatus, avg(totalSpent) from receipts group by rewardsreceiptstatus )'''

In [94]:
cursor.execute(count)
new = cursor.fetchall()
for n in new:
    print(n)

('REJECTED', 19.544970059880253)
('SUBMITTED', None)
('FLAGGED', 2635.5702469136068)
('PENDING', 28.03244897959184)
('FINISHED', 1244.372934121628)

## A) Looking at the data in above cell, the average spend from receipts with 'rewardsReceiptStatus’ = FINISED is 1244.373 and with 'rewardsReceiptStatus’ = REJECTED is 19.545, therefore for average spend from receipts with 'rewardsReceiptStatus’ = FINISED  is greater

## Q) When considering total number of items purchased from receipts with 'rewardsReceiptStatus’ of ‘Accepted’ or ‘Rejected’, which is greater?

In [95]:
item_purchased = '''(select rewardsreceiptstatus, sum(purchaseditemcount) from receipts group by rewardsreceiptstatus )'''

In [96]:
cursor.execute(item_purchased)
new = cursor.fetchall()
for n in new:
    print(n)

('REJECTED', 740.0)
('SUBMITTED', None)
('FLAGGED', 294816.0)
('PENDING', None)
('FINISHED', 1364998.0)

## A) Looking at the data in above cell, total number of items purchased from receipts with 'rewardsReceiptStatus’ = FINISED is 1364998.0 and with 'rewardsReceiptStatus’ = REJECTED is 740.0, therefore total number of items purchased from receipts with 'rewardsReceiptStatus’ = FINISED  is greater

# Data Quality Issues

Looking at the 3 raw datasets provided I observed there are certain data quality issues such as:
1) Incomplete fields
2) Inconsistent format
3) Different measurement units 
3) Lack of information or poorly defined data

1) Incompleted fields: The dataset contains "NaN" values as shown in dataset.info(). I believe that answering many business questions can be misleading because there is not sufficient information in the data. 

2) Inconsistent format: The dataset has a different format. for example "_id" in every dataset is in a dictionary, which is not required. It can be in a simple list form so that the cleaning process will be reduced and hence improve optimization. 

3) Different measurement units: The date format in every dataset is in a different form and loaded in the dictionary. It has to be in DateTime format. This can make reading, extraction of data much easier and help answer many business questions in terms of date. 

4) Lack of information or poorly defined data: There is no particular field that can join brands table to receipts table. Although we can connect brands table to receipt table via bridge having "barcode" as the primary key. But it does not follow the main rule of the primary key, which is to not have any null values. Instead, it is better to have a brand_id in the receipts table, so that the primary key is not null and does not require a bridge to join, which can help to optimize query retrieval.

# Communicate with Stakeholders

#### Question:
Construct an email or slack message that is understandable to a product or business leader who isn’t familiar with your day to day work. This part of the exercise should show off how you communicate and reason about data with others. Commit your answers to the git repository along with the rest of your exercise.

What questions do you have about the data?


How did you discover the data quality issues?
What do you need to know to resolve the data quality issues?
What other information would you need to help you optimize the data assets you're trying to create?
What performance and scaling concerns do you anticipate in production and how do you plan to address them?

Answer: 

Hi,
I am Anuj Rathod, currently working with the data analytics team on a project where I am responsible for building a relational database for different datasets like receipts, users, brands in a warehouse to analyze some of the business questions.
During my analysis, I faced some issues which might affect the overall performance. I would like to address some of my data quality concerns with you or someone from your team so that we can successfully meet our deliverables without compromising the quality of the results. 

For a part of my analysis, I had to join tables (receipts & brands) and figured there is no relation between the table based on which a relationship can be established, although I was able to connect them with another field, I do not think it is the best option to go for. 

There were some columns that I was not able to interpret as there was no data dictionary for rewardsreceiptitemlist column in the receipts dataset to refer to. Understanding all the fields in the dataset can help expedite the data analysis process.
I believe that reevaluating the source of data might help us overcome some of these problems. 

Also understanding the impact of analysis will help define boundaries for expectations for this project. I wanted to better understand when, how, and why this data is used? This information will help the analysis work better for an optimized process. Let me know your thought, please let me know I could answer any questions to provide more clarity.